import assert from 'node:assert/strict';
import { describe, it } from 'node:test';
import { getDialects } from '@polyglot-sql/sdk';
import { describeQuery } from '../dist/describe.js';

import type { DescribeResult, ValidationSchema } from '../dist/types.js';

const coverageSchema: ValidationSchema = {
  tables: [
    {
      name: 'users',
      columns: [
        { name: 'id', type: 'integer' },
        { name: 'name', type: 'text' },
        { name: 'age', type: 'integer' },
        { name: 'dept', type: 'text' },
        { name: 'data', type: 'json' },
        { name: 'geom', type: 'geometry' },
        { name: 'geog', type: 'geography' },
        { name: 'a', type: 'integer' },
        { name: 'b', type: 'integer' },
        { name: 'created_at', type: 'timestamp' },
        { name: 'd', type: 'date' },
        { name: 'tags', type: 'array<text>' },
        { name: 'attrs', type: 'map<text, integer>' },
      ],
    },
    {
      name: 'orders',
      columns: [
        { name: 'id', type: 'integer' },
        { name: 'user_id', type: 'integer' },
        { name: 'amount', type: 'decimal' },
      ],
    },
    {
      name: 'src',
      columns: [
        { name: 'id', type: 'integer' },
        { name: 'name', type: 'text' },
      ],
    },
  ],
};

const staticResultCases = [
  ['generic', 'select id, name from users'],
  ['generic', "select reverse(name) r, initcap(name) i, concat_ws(',', name, name) c from users"],
  ['generic', 'select u.id, o.amount from users u join orders o on o.user_id = u.id'],
  ['generic', 'select id, name from users where exists (select 1 from orders where orders.user_id = users.id)'],
  ['hive', 'select id, name from users'],
  ['databricks', 'select id, name from users'],
  ['databricks', 'describe detail users'],
  ['databricks', 'describe history users'],
  ['athena', 'select id, name from users'],
  ['teradata', 'select top 5 id, name from users'],
  ['doris', 'select id, name from users'],
  ['starrocks', 'select id, name from users'],
  ['materialize', 'select id, name from users'],
  ['materialize', 'show clusters'],
  ['materialize', 'show sources'],
  ['materialize', 'show sinks'],
  ['risingwave', 'select id, name from users'],
  ['singlestore', 'select id, name from users'],
  ['singlestore', 'show pipelines'],
  ['cockroachdb', 'select id, name from users'],
  ['cockroachdb', 'show constraints from users'],
  ['cockroachdb', 'show jobs'],
  ['tidb', 'select id, name from users'],
  ['solr', 'select id, name from users'],
  ['tableau', 'select id, name from users'],
  ['dune', 'select id, name from users'],
  ['fabric', 'select top 5 id, name from users'],
  ['drill', 'select id, name from users'],
  ['drill', 'show files'],
  ['dremio', 'select id, name from users'],
  ['exasol', 'select id, name from users'],
  ['exasol', 'select * from exa_all_tables'],
  ['datafusion', 'select id, name from users'],
  ['postgres', 'select * from generate_series(1,3)'],
  ['postgres', 'select * from pg_catalog.pg_get_keywords() as k'],
  ['postgres', "select * from pg_catalog.pg_options_to_table(ARRAY['fillfactor=70']) as o"],
  ['postgres', 'select * from pg_catalog.pg_stat_get_activity(null) as a'],
  ['postgres', "select * from pg_catalog.pg_get_object_address('table', ARRAY['users'], ARRAY[]::text[]) as a"],
  ['postgres', 'select * from pg_settings as s'],
  ['postgres', 'select * from pg_stat_activity as a'],
  ['postgres', 'select * from pg_catalog.pg_roles'],
  ['postgres', 'select * from pg_catalog.pg_indexes'],
  ['postgres', 'select * from pg_catalog.pg_locks'],
  ['postgres', 'select * from pg_catalog.pg_user'],
  ['postgres', 'select * from pg_catalog.pg_views'],
  ['postgres', 'select extname from pg_catalog.pg_extension'],
  ['postgres', 'select typname from pg_catalog.pg_type'],
  ['postgres', 'select proname from pg_catalog.pg_proc'],
  ['postgres', 'select conname from pg_catalog.pg_constraint'],
  ['postgres', 'select attname from pg_catalog.pg_attribute'],
  ['postgres', 'select idx_scan from pg_catalog.pg_stat_user_indexes'],
  ['postgres', 'select relname from pg_stat_user_tables'],
  ['postgres', 'select datname from pg_stat_database'],
  ['postgres', 'select relname from pg_class'],
  ['postgres', 'select nspname from pg_namespace'],
  ['postgres', "select * from current_setting('search_path') as s"],
  ['postgres', "select * from json_each_text('{\"a\":1}') as x"],
  ['postgres', 'select * from jsonb_each(\'{"a":1}\'::jsonb) as e'],
  ['postgres', "select * from json_populate_record(null::users, '{\"id\":1}') as x"],
  ['postgres', "select * from pg_logical_slot_get_changes('slot', null, null) as c"],
  ['postgres', "select * from ts_debug('english', 'a fat cat') as t"],
  ['postgres', "select * from pg_stat_file('base') as s"],
  ['postgres', "select * from pg_read_file('x') as f"],
  ['postgres', 'select * from pg_ls_waldir() as w'],
  ['postgres', 'select * from pg_ls_logdir() as l'],
  ['postgres', 'select * from pg_timezone_names() as tz'],
  ['postgres', 'select * from pg_available_extension_versions() as e'],
  ['postgres', "select e.key, e.value from users, json_each(data) as e"],
  ['postgres', "select elem from users, json_array_elements_text(data) as elem"],
  ['postgres', "select to_char(created_at, 'YYYY') c from users"],
  ['postgres', 'select array(select id from users) a'],
  ['postgres', 'show all'],
  ['postgres', 'show search_path'],
  ['postgres', 'show transaction isolation level'],
  ['postgres', 'select stddev(age) sd, variance(age) v, mode() within group (order by age) m from users'],
  ['postgres', 'select percentile_cont(0.5) within group (order by age) p from users'],
  ['postgres', 'select json_arrayagg(name) ja, json_objectagg(name, age) jo from users'],
  ['postgres', 'select bit_and(age) ba, bit_or(age) bo, bit_xor(age) bx from users'],
  ['postgres', 'select regr_count(age, id) rc, regr_avgx(age, id) rax, regr_avgy(age, id) ray from users'],
  ['postgres', 'select ntile(4) over(order by age) nt from users'],
  ['postgres', 'select distinct on (dept) dept, name from users order by dept, age desc'],
  ['postgres', "select left(name,2) l, right(name,2) r, repeat(name,2) rp, regexp_match(name,'a') rm from users"],
  ['postgres', "select levenshtein(name,'x') l from users"],
  ['postgres', "select pg_typeof(age) pt, format('%s', name) f, to_regclass(name) tr from users"],
  ['postgres', "select overlay(name placing 'x' from 1 for 1) o, ascii(name) a, chr(age) c from users"],
  ['postgres', "select quote_nullable(name) qn, parse_ident(name) pi, regexp_split_to_table(name, ',') rst from users"],
  ['postgres', 'select width_bucket(age,0,100,10) wb, num_nonnulls(name,age) nn, num_nulls(name,age) nl from users'],
  ['postgres', "select array_dims(tags) ad, array_ndims(tags) an, jsonb_extract_path_text(data::jsonb,'x') jpt from users"],
  ['postgres', "select row_to_json(users) rj, jsonb_path_query(data::jsonb,'$.x') jp from users"],
  ['postgres', "select tags && array['a'] ov, tags @> array['a'] ca, tags <@ array['a','b'] cb from users"],
  ['postgres', 'select tags[1] t, tags[1:2] ts from users'],
  ['postgres', 'select (id, name) as r from users'],
  ['postgres', "select to_tsvector(name) tv, setweight(to_tsvector(name),'A') sw, websearch_to_tsquery(name) wq from users"],
  ['postgres', "select array_prepend('x',tags) ap, array_replace(tags,'x','y') ar from users"],
  ['postgres', 'select st_asbinary(geom) b, st_asgeojson(geom) gj, st_srid(geom) srid from users'],
  ['postgres', 'select st_npoints(geom) np, st_ndims(geom) nd, st_dimension(geom) dim from users'],
  ['postgres', 'select st_setsrid(geom,4326) sg, st_transform(geom,3857) tg, st_makeenvelope(0,0,1,1,4326) env from users'],
  ['postgres', "select gen_random_bytes(4) grb, digest(name,'sha256') dg, hmac(name,'k','sha256') hm from users"],
  ['postgres', "select encode(decode(name,'hex'),'base64') e from users"],
  ['postgres', "select greatest(age,1) g, least(age,2) l, make_interval(days => age) mi from users"],
  ['postgres', 'select cbrt(age) c, div(age,2) d, factorial(age) f from users'],
  ['postgres', 'select inet_client_addr() ica, inet_server_port() isp, pg_backend_pid() pid, txid_current() tx from users'],
  ['postgres', "select date_bin('1 hour', created_at, timestamp '2020-01-01') db, justify_interval(age(created_at)) ji from users"],
  ['postgres', 'select clock_timestamp() ct, statement_timestamp() st, transaction_timestamp() tt, current_schema() cs from users'],
  ['postgres', "copy (select id, name from users) to '/tmp/users.csv'"],
  ['postgres', "insert into users(id,name) values (1,'a') returning id, name"],
  ['postgres', "update users set name='b' returning id, name"],
  ['postgres', "update users set name='b' returning old.name, new.name"],
  ['postgres', 'delete from users returning id'],
  ['postgres', "merge into users using src on users.id=src.id when matched then update set name=src.name returning users.*, src.name"],
  ['mysql', 'show create function f'],
  ['mysql', 'show engine innodb status'],
  ['mysql', 'show full processlist'],
  ['mysql', 'show table status'],
  ['mysql', 'show relaylog events'],
  ['mysql', 'select * from information_schema.processlist'],
  ['mysql', 'select variable_name from performance_schema.global_variables'],
  ['mysql', 'select EVENT_NAME from information_schema.EVENTS'],
  ['mysql', "select str_to_date(name, '%Y-%m-%d') d from users"],
  ['mysql', "select json_unquote(json_extract(data, '$.x')) x, json_contains(data, '{}') c, unhex(hex(name)) b, aes_encrypt(name, 'k') e from users"],
  ['mysql', "select json_valid(data) jv, make_set(age,'a','b') ms, export_set(age,'Y','N') es from users"],
  ['mysql', "select date_format(d,'%Y') df, format(age,2) f, bin(age) b, uuid() u from users"],
  ['mysql', "select json_array(id,name) ja, json_object('id',id) jo, json_type(data) jt, json_length(data) jl from users"],
  ['mysql', "select json_set(data,'$.x',1) js, json_insert(data,'$.x',1) ji, json_remove(data,'$.x') jr, json_merge_patch(data,data) jm from users"],
  ['mysql', "select cast(name as json) j, json_keys(data) jk, json_search(data,'one','x') js from users"],
  ['mysql', "select soundex(name) s, space(age) sp, find_in_set(name, 'a,b') f from users"],
  ['mysql', "select substring_index(name, ',', 1) si, day(d) dy, month(d) mo, year(d) yr, unix_timestamp(created_at) ut from users"],
  ['mysql', 'select degrees(age) d, radians(age) r, truncate(age, 1) t from users'],
  ['mysql', 'select age div 2 d from users'],
  ['mysql', 'select md5(name) m, sha1(name) s1, sha2(name,256) s2, password(name) p from users'],
  ['mysql', 'select inet6_aton(name) ia6, inet6_ntoa(inet6_aton(name)) in6 from users'],
  ['mysql', 'select bit_count(age) bc, connection_id() cid, last_insert_id() li, is_ipv4(name) ip4, is_ipv6(name) ip6 from users'],
  ['mysql', 'select stddev_pop(age) sp, var_pop(age) vp, bit_and(age) ba, bit_or(age) bo from users'],
  ['sqlite', 'pragma wal_checkpoint'],
  ['sqlite', 'pragma foreign_key_check'],
  ['sqlite', 'pragma table_list'],
  ['sqlite', 'pragma reverse_unordered_selects'],
  ['sqlite', "select * from pragma_table_info('users')"],
  ['sqlite', 'select changes() ch, total_changes() tc, last_insert_rowid() lr, sqlite_version() sv'],
  ['sqlite', 'select typeof(name) t, quote(name) q, zeroblob(age) zb from users'],
  ['sqlite', "insert into users(id,name) values (1,'a') returning id"],
  ['sqlite', "update users set name='b' returning id"],
  ['sqlite', 'delete from users returning id'],
  ['duckdb', 'pragma show_tables'],
  ['duckdb', 'pragma version'],
  ['duckdb', 'pragma database_size'],
  ['duckdb', 'pragma platform'],
  ['duckdb', 'pragma functions'],
  ['duckdb', 'pragma collations'],
  ['snowflake', 'describe warehouse wh'],
  ['snowflake', 'describe database db'],
  ['snowflake', 'describe schema public'],
  ['snowflake', 'describe stream s'],
  ['snowflake', 'show primary keys'],
  ['snowflake', 'list @stage'],
  ['snowflake', 'put file://tmp/a.csv @stage'],
  ['snowflake', 'get @stage file://tmp/'],
  ['snowflake', 'remove @stage/a.csv'],
  ['snowflake', 'copy into @stage from users'],
  ['snowflake', 'copy into @stage from (select id, name from users)'],
  ['snowflake', 'select query_id from account_usage.query_history'],
  ['snowflake', 'select column_name from account_usage.columns'],
  ['snowflake', 'select database_name from account_usage.databases'],
  ['snowflake', 'select schema_name from account_usage.schemata'],
  ['snowflake', 'select function_name from information_schema.functions'],
  ['snowflake', 'select try_to_number(name) n from users'],
  ['snowflake', "select object_construct('id', id, 'name', name) o, array_construct(id, age) a from users"],
  ['snowflake', 'select parse_json(name) j, check_json(name) c, is_null_value(parse_json(name)) n from users'],
  ['snowflake', 'select system$typeof(name) st, typeof(parse_json(name)) tf from users'],
  ['snowflake', 'select current_version() cv, current_account() ca, current_region() cr, current_role() role from users'],
  ['snowflake', "select charindex('a', name) ci, editdistance(name,'x') ed from users"],
  ['snowflake', 'select data:x j, data:x::string s from users'],
  ['snowflake', "select split(name, ',') s, array_size(split(name,',')) n, get(parse_json(name),'x') g from users"],
  ['snowflake', 'select object_keys(parse_json(name)) ok from users'],
  ['snowflake', "select object_insert(object_construct('id', id),'x',1) oi, json_array_append(data,'$.x',1) jaa, json_array_insert(data,'$.x',1) jai, json_array_contains(data,'x') jac from users"],
  ['snowflake', 'select array_flatten(array_construct(tags)) af, array_compact(tags) ac, array_intersect(tags,tags) ai, array_union(tags,tags) au, array_except(tags,tags) ae from users'],
  ['snowflake', 'select array_contains_all(tags,tags) aca, array_contained_by(tags,tags) acb, array_overlaps(tags,tags) ao from users'],
  ['snowflake', 'select array_zip(tags, array_construct(age)) az, array_all(tags, x -> x is not null) aa, array_any(tags, x -> x is not null) anyv from users'],
  ['snowflake', 'select to_varchar(age) tv, to_binary(name) tb, md5_binary(name) mb, sha2_binary(name) sb from users'],
  ['snowflake', 'select to_timestamp(name) ts, to_date(name) d, to_time(name) t, to_boolean(name) b from users'],
  ['snowflake', 'select datediff(day, created_at, created_at) dd, dateadd(day, 1, created_at) da, last_day(d) ld from users'],
  ['snowflake', "select nvl2(name, age, id) n2, regexp_like(name,'a') rl from users"],
  ['snowflake', 'select ratio_to_report(age) over(partition by dept) rr from users'],
  ['snowflake', 'select to_geography(name) g, to_geometry(name) gm, st_distance(geog, geog) dist from users'],
  ['snowflake', 'select cosine_distance(geom, geom) cd, euclidean_distance(geom, geom) ed, manhattan_distance(geom, geom) md from users'],
  ['snowflake', 'select hash(name) h, hash_agg(name) ha, uuid_string() u from users'],
  ['snowflake', "select try_to_decfloat(name) td, ai_agg(name, 'summarize') aa, ai_classify(name, ['a','b']) ac, ml_forecast(age) mf from users"],
  ['snowflake', 'select try_base64_decode_string(name) s, try_base64_decode_binary(name) b from users'],
  ['snowflake', 'select base64_encode(name) e, base64_decode_string(name) ds, base64_decode_binary(name) db from users'],
  ['snowflake', 'select compress(name) c, decompress_binary(name) db, decompress_string(name) ds, parse_url(name) pu, check_xml(name) cx from users'],
  ['snowflake', "select * from table(infer_schema(location=>'@mystage', file_format=>'ff'))"],
  ['snowflake', "select f.key, f.value from users, lateral flatten(input => parse_json(name)) f"],
  ['snowflake', 'select object_agg(name, age) o from users'],
  ['snowflake', 'select id, row_number() over(order by age) rn from users qualify rn = 1'],
  ['snowflake', "execute immediate 'select 1 as id'"],
  ['bigquery', 'select * from unnest(generate_array(1,3)) as x'],
  ['bigquery', 'select tag, off from users, unnest(tags) as tag with offset as off'],
  ['bigquery', 'select (select as struct id, name) s from users'],
  ['bigquery', 'select safe_add(age, 1) a, safe_divide(age, 2) d from users'],
  ['bigquery', 'select ieee_divide(age, 2) idv, is_inf(ieee_divide(age,0)) inf, is_nan(ieee_divide(age,0)) nan from users'],
  ['bigquery', 'select current_datetime() dt, current_timestamp() ts, current_time() tm'],
  ['bigquery', 'select approx_count_distinct(name) acd, any_value(name) av from users'],
  ['bigquery', 'select approx_quantiles(age, 10) aq, array_concat_agg(tags) ac from users'],
  ['bigquery', "select json_query_array(data,'$.x') jqa, json_value_array(data,'$.x') jva from users"],
  ['bigquery', "select generate_embedding(model => 'm', content => name) ge, ai_classify(name, ['a','b']) ac from users"],
  ['bigquery', 'select generate_uuid() u, farm_fingerprint(name) f, to_base64(from_base64(name)) b from users'],
  ['bigquery', "select starts_with(name,'a') sw, ends_with(name,'z') ew, regexp_extract_all(name,'[a-z]') xs from users"],
  ['bigquery', 'select ascii(name) a, chr(age) c, code_points_to_string([65,66]) cps from users'],
  ['bigquery', "select to_code_points(name) tcp, split(name, ',') s, byte_length(name) bl from users"],
  ['bigquery', 'select date(d) dd, timestamp(created_at) ts, datetime(created_at) dt, time(created_at) tm from users'],
  ['bigquery', 'select unix_seconds(created_at) us from users'],
  ['bigquery', 'select array_length(tags) l, array_reverse(tags) r, array_concat(tags,tags) c from users'],
  ['bigquery', "select array_to_string(tags, ',') ats, array_first(tags) af, array_last(tags) al from users"],
  ['bigquery', "select data['x'] j, tags[offset(0)] tag from users"],
  ['bigquery', 'select * except(age) replace(age + 1 as id) from users'],
  ['bigquery', "execute immediate 'select 1 as id'"],
  ['bigquery', "export data options(uri='gs://b/x.csv') as select id, name from users"],
  ['bigquery', 'select project_id from information_schema.schemata'],
  ['bigquery', 'select table_id from __TABLES__'],
  ['bigquery', 'select * from __TABLES_SUMMARY__'],
  ['tsql', 'select session_id from sys.dm_exec_requests'],
  ['tsql', 'select @@spid spid, db_name() db, host_name() host, app_name() app'],
  ['tsql', "select checksum(name) cs, binary_checksum(name) bc, patindex('%a%', name) pi from users"],
  ['tsql', "select * from string_split('a,b', ',')"],
  ['tsql', "select * from openjson('{\"a\":1}') with (a int '$.a')"],
  ['tsql', "select * from openquery(server, 'select 1 as id')"],
  ['tsql', 'exec sp_help users'],
  ['tsql', 'sp_help users'],
  ['tsql', 'execute sp_who'],
  ['tsql', 'exec sp_spaceused users'],
  ['tsql', 'exec sp_tables'],
  ['tsql', 'exec sp_columns users'],
  ['tsql', 'exec sp_databases'],
  ['tsql', 'exec dbo.my_proc with result sets ((id int, name nvarchar(20)))'],
  ['tsql', "insert into users(id,name) output inserted.id, inserted.name values (1,'a')"],
  ['tsql', "update users set name='b' output inserted.id, deleted.name"],
  ['tsql', 'delete from users output deleted.id'],
  ['tsql', 'merge into users as t using users as s on t.id=s.id when matched then update set name=s.name output inserted.id, deleted.name'],
  ['oracle', 'select sid from v$session'],
  ['oracle', 'select username from all_users'],
  ['oracle', 'select column_name from all_tab_columns'],
  ['oracle', 'select object_name from all_objects'],
  ['oracle', 'select view_name from all_views'],
  ['oracle', 'select constraint_name from all_constraints'],
  ['oracle', 'select constraint_name from user_constraints'],
  ['oracle', 'select table_name from user_tables'],
  ['oracle', 'select object_name from user_objects'],
  ['oracle', 'select sysdate sd, systimestamp st, user u from dual'],
  ['oracle', "select decode(age,1,'one','other') d, dump(name) dumpv from users"],
  ['oracle', 'select add_months(d,1) am, last_day(d) ld, months_between(d,d) mb from users'],
  ['oracle', 'select * from json_table(\'{\"a\":1}\', \'$\' columns (a number path \'$.a\')) jt'],
  ['oracle', "select * from table(sys.odcivarchar2list('a','b')) t"],
  ['oracle', 'select * from users match_recognize (partition by dept order by created_at measures match_number() as match_no, classifier() as cls all rows per match pattern (A+) define A as age > 0) mr'],
  ['duckdb', 'select * from duckdb_tables()'],
  ['duckdb', 'select * from duckdb_settings()'],
  ['duckdb', 'select * from duckdb_extensions()'],
  ['duckdb', 'select * from duckdb_databases()'],
  ['duckdb', 'select * from duckdb_constraints()'],
  ['duckdb', 'select * from duckdb_keywords()'],
  ['duckdb', 'select * from duckdb_types()'],
  ['duckdb', 'select * from duckdb_memory()'],
  ['duckdb', "select * from glob('*.csv')"],
  ['duckdb', "select * from read_blob('x')"],
  ['duckdb', "select * from read_text('x')"],
  ['duckdb', "select * from read_csv('x', columns={'id':'INTEGER','name':'VARCHAR'})"],
  ['duckdb', "select * from read_json('x', columns={'id':'INTEGER','name':'VARCHAR'})"],
  ['duckdb', "select * from parquet_schema('x.parquet')"],
  ['duckdb', "select * from parquet_metadata('x.parquet')"],
  ['duckdb', 'select list_value(id, age) xs, struct_pack(id := id, name := name) s from users'],
  ['duckdb', 'select typeof(name) t, stats(age) st, version() v from users'],
  ['duckdb', 'select list_transform(tags, x -> upper(x)) t from users'],
  ['duckdb', "select contains(tags,'a') c, list_contains(tags,'a') lc, list_extract(tags,1) le from users"],
  ['duckdb', "select name.lower() l, name.upper() u, tags.list_contains('a') c, tags.list_extract(1) e from users"],
  ['duckdb', "select list_has(tags,'a') lh, list_has_all(tags,tags) lha, list_has_any(tags,tags) lhan from users"],
  ['duckdb', "select prefix(name,'a') p, suffix(name,'z') s, list_position(tags,'x') lp, list_unique(tags) lu from users"],
  ['duckdb', 'select epoch(created_at) e, epoch_ms(created_at) ems, make_date(2020,1,1) md from users'],
  ['duckdb', 'select last_day(d) ld, list_slice(tags, 1, 2) ls, list_reverse(tags) lr, list_concat(tags,tags) lc from users'],
  ['duckdb', 'select histogram(age) h, entropy(age) e, product(age) p from users'],
  ['duckdb', "select regexp_extract_all(name, '[a-z]+') r, regexp_split(name, ',') s from users"],
  ['duckdb', "select json_extract(data,'$.x') je, json_extract_string(data,'$.x') jes, json_type(data) jt from users"],
  ['duckdb', "select regexp_full_match(name, '[a-z]+') fm, regexp_instr(name, 'a') ri from users"],
  ['duckdb', 'pivot users on dept using sum(age)'],
  ['duckdb', 'unpivot users on a,b into name k value v'],
  ['clickhouse', 'show databases'],
  ['clickhouse', 'describe table users'],
  ['clickhouse', 'show create table users'],
  ['clickhouse', 'show create database default'],
  ['clickhouse', 'show create dictionary d'],
  ['clickhouse', 'show processlist'],
  ['clickhouse', 'show clusters'],
  ['clickhouse', 'show users'],
  ['clickhouse', 'show roles'],
  ['clickhouse', 'show grants'],
  ['clickhouse', 'show settings'],
  ['clickhouse', 'show dictionaries'],
  ['clickhouse', 'show functions'],
  ['clickhouse', 'select name from system.functions'],
  ['clickhouse', 'select query from system.query_log'],
  ['clickhouse', 'select name from information_schema.tables'],
  ['clickhouse', 'exists table users'],
  ['clickhouse', 'explain ast select id from users'],
  ['clickhouse', 'select * from numbers(3)'],
  ['clickhouse', 'select * from numbers_mt(3)'],
  ['clickhouse', 'select cityHash64(name) h, toString(age) s, toDate(name) d from users'],
  ['clickhouse', 'select version() v, currentDatabase() db, currentUser() u, sipHash64(name) sh, bitCount(age) bc from users'],
  ['clickhouse', 'select toInt32(name) i, toFloat64(name) f, toUUID(name) u, toBool(age) b from users'],
  ['clickhouse', "select has(tags,'a') h, length(tags) l, arrayJoin(tags) tag from users"],
  ['clickhouse', "select arrayStringConcat(tags,',') asc, empty(tags) e, notEmpty(tags) ne from users"],
  ['clickhouse', 'select mapKeys(attrs) mk, mapValues(attrs) mv from users'],
  ['clickhouse', "select multiIf(age > 0, name, 'x') mi, ifNull(name,'x') n from users"],
  ['clickhouse', "select replaceRegexpAll(name,'a','b') rr, match(name,'a') m from users"],
  ['clickhouse', "select JSONExtractString(name,'id') js, JSONExtractInt(name,'id') ji, JSONHas(name,'id') jh from users"],
  ['clickhouse', "select toStartOfDay(created_at) sd, formatDateTime(created_at,'%F') fd from users"],
  ['clickhouse', 'select addDays(d, 1) ad, toYear(d) y, lowerUTF8(name) l, upperUTF8(name) u from users'],
  ['clickhouse', "select * from file('a.csv', CSV, 'id UInt64, name String')"],
  ['clickhouse', "select * from url('http://example.com/a.csv', CSV, 'id UInt64, name String')"],
  ['clickhouse', 'watch users'],
  ['presto', 'select * from sequence(1,3) as t(x)'],
  ['trino', "select * from unnest(map(array['a'], array[1])) as t(k, v)"],
  ['trino', "select transform(tags, x -> upper(x)) t, filter(tags, x -> x <> 'a') f from users"],
  ['trino', 'select reduce(array[1,2], 0, (s, x) -> s + x, s -> s) r'],
  ['trino', "select any_match(tags, x -> x = 'a') a, all_match(tags, x -> x <> '') b, none_match(tags, x -> x = 'z') n from users"],
  ['trino', "select json_extract(data,'$.x') j, json_extract_scalar(data,'$.x') s, contains(tags,'a') c from users"],
  ['trino', "select element_at(attrs,'a') ea, map_keys(attrs) mk, map_values(attrs) mv from users"],
  ['trino', "select tags[1] tag, data['x'] j from users"],
  ['trino', "select strpos(name,'a') sp, codepoint(name) cp, chr(age) ch, regexp_like(name,'a') rl, regexp_position(name,'a') rp from users"],
  ['trino', "select url_extract_host(name) h, url_encode(name) ue, from_utf8(to_utf8(name)) fu from users"],
  ['trino', "select last_day_of_month(d) lm, lpad(name, 5, 'x') lp, rpad(name,5,'x') rp from users"],
  ['trino', 'select checksum(name) c, geometric_mean(age) gm, map_agg(name, age) ma from users'],
  ['trino', 'show stats for users'],
  ['spark', 'describe function abs'],
  ['spark', 'describe database default'],
  ['spark', 'describe namespace default'],
  ['spark', 'describe table extended users'],
  ['spark', 'show current namespace'],
  ['spark', 'list file'],
  ['spark', 'select id, pos, tag from users lateral view posexplode(tags) e as pos, tag'],
  ['spark', 'select * from explode(array(1,2)) as t'],
  ['spark', "select size(tags) sz, array_contains(tags, 'x') has from users"],
  ['spark', "select transform(tags, x -> upper(x)) t from users"],
  ['spark', "select array_join(tags, ',') j, array_sort(tags) s from users"],
  ['spark', "select instr(name,'a') i, locate('a', name) l, soundex(name) s from users"],
  ['spark', "select last_day(d) ld, lpad(name, 5, 'x') lp, rpad(name,5,'x') rp from users"],
  ['spark', "select parse_url(name,'HOST') host from users"],
  ['spark', "select nvl2(name, age, id) n2, rlike(name,'a') rl from users"],
  ['spark', "select array_position(tags,'x') ap, array_distinct(tags) ad, array_remove(tags,'x') ar from users"],
  ['spark', "select exists(tags, x -> x = 'a') e, forall(tags, x -> x <> '') f from users"],
  ['spark', "select map_concat(attrs, map('b',2)) m from users"],
  ['spark', "select element_at(attrs,'a') ea, map_keys(attrs) mk, map_values(attrs) mv from users"],
  ['spark', "select tags[0] tag, data['x'] j from users"],
  ['spark', "select from_json(name, 'id INT, name STRING') j, to_json(named_struct('id', id)) tj from users"],
  ['spark', "select get_json_object(name,'$.id') g, json_tuple(name,'id') jt from users"],
  ['spark', 'select collect_list(name) cl, collect_set(name) cs, percentile_approx(age, 0.5) pa from users'],
  ['spark', 'select current_database() db, current_user() u, version() v, hash(name) h, xxhash64(name) xx from users'],
  ['hive', 'show databases'],
  ['hive', 'select current_database() db, current_user() u, version() v, pmod(age,2) pm, conv(name,10,16) cv from users'],
  ['hive', 'select * from explode(array(1,2)) as t'],
  ['databricks', 'show catalogs'],
  ['athena', 'show tables'],
  ['cockroachdb', 'show databases'],
  ['materialize', 'show views'],
  ['risingwave', 'show tables'],
  ['teradata', 'help table users'],
  ['teradata', 'help database db'],
  ['teradata', 'help column users.*'],
  ['redshift', 'select table_name from svv.tables'],
  ['redshift', 'select tablename from pg_catalog.svv_tables'],
  ['redshift', 'select query from stl_query'],
  ['druid', 'select segment_id from sys.segments'],
] as const;

const noResultCases = [
  ['postgres', 'lock table users'],
  ['postgres', 'alter sequence user_id_seq restart with 1'],
  ['mysql', 'flush tables'],
  ['mysql', 'kill 1'],
  ['sqlite', 'vacuum'],
  ['duckdb', 'install httpfs'],
  ['duckdb', 'checkpoint'],
  ['snowflake', 'undrop table users'],
  ['snowflake', 'merge into users using src on users.id=src.id when matched then update set name=src.name'],
  ['spark', 'msck repair table users'],
  ['spark', "load data local inpath '/tmp/x' into table users"],
  ['spark', 'dfs -ls /tmp'],
  ['tsql', "raiserror ('x', 16, 1)"],
  ['teradata', "set query_band='app=sqldesc;' for session"],
] as const;

const schemaTrackingCases = [
  ['postgres', 'create schema app; create table app.people(id int, name text); select id, name from app.people'],
  ['postgres', "create table t(id int generated always as identity, name text default 'x', created_at timestamp not null); select id, name, created_at from t"],
  ['postgres', 'create table people(id int, name text); alter table people set schema app; select id, name from app.people'],
  ['postgres', 'create table people(id int, name text); create view app_people as select id, name from people; alter view app_people rename to people_view; select name from people_view'],
  ['postgres', 'create table people(id int, name text); create synonym p for people; select name from p'],
  ['tsql', 'create table dbo.people(id int, name varchar(20)); select name from dbo.people'],
  ['tsql', 'create table t(id int identity(1,1) primary key, name nvarchar(20) not null, amount decimal(10,2)); select id, name, amount from t'],
  ['tsql', 'create synonym p for users; select name from p'],
  ['mysql', 'create table t(id int auto_increment primary key, name varchar(20) not null, amount decimal(10,2)); select id, name, amount from t'],
  ['bigquery', 'create table t(id int64, name string, amount numeric); select id, name, amount from t'],
  ['oracle', 'create global temporary table t(id number, name varchar2(20)) on commit preserve rows; select id, name from t'],
  ['duckdb', 'create macro people_macro() as table select id, name from users; select name from people_macro()'],
] as const;

describe('polyglot representative SQL coverage', () => {
  for (const dialect of getDialects()) {
    it(`describes a schema-backed SELECT for supported dialect: ${dialect}`, async () => {
      const result = await describeQuery({
        dialect,
        sql: 'select id, name from users',
        schema: coverageSchema,
      });

      assert.strictEqual(result.statements[0]?.resultKind, 'static');
      assert.deepStrictEqual(result.columns.map((column) => [column.name, column.type, column.source]), [
        ['id', 'integer', 'users.id'],
        ['name', 'text', 'users.name'],
      ]);
      assert.deepStrictEqual(result.warnings, []);
    });
  }

  for (const dialect of getDialects()) {
    for (const sql of ['show tables', 'show schemas'] as const) {
      it(`statically describes ${sql} for supported dialect: ${dialect}`, async () => {
        const result = await describeQuery({ dialect, sql, schema: coverageSchema });

        assert.strictEqual(result.statements[0]?.resultKind, 'static');
        assert.ok(result.columns.length > 0);
        assert.strictEqual(unresolvedColumnCount(result), 0);
        assert.deepStrictEqual(result.warnings, []);
      });
    }
  }

  for (const [dialect, sql] of staticResultCases) {
    it(`statically describes ${dialect}: ${sql}`, async () => {
      const result = await describeQuery({ dialect, sql, schema: coverageSchema });

      assert.strictEqual(result.statements[0]?.resultKind, 'static');
      assert.ok(result.columns.length > 0);
      assert.ok(result.columns.length < 80);
      assert.strictEqual(unresolvedColumnCount(result), 0);
      assert.deepStrictEqual(result.warnings, []);
      assert.deepStrictEqual(result.diagnostics, []);
    });
  }

  for (const [dialect, sql] of noResultCases) {
    it(`classifies no-result ${dialect}: ${sql}`, async () => {
      const result = await describeQuery({ dialect, sql, schema: coverageSchema });

      assert.deepStrictEqual(result.columns, []);
      assert.strictEqual(result.statements[0]?.resultKind, 'none');
    });
  }

  for (const [dialect, sql] of schemaTrackingCases) {
    it(`tracks schema changes for ${dialect}: ${sql}`, async () => {
      const result = await describeQuery({ dialect, sql, schema: coverageSchema });
      const lastStatement = result.statements.at(-1);
      const lastResultSet = result.resultSets.at(-1);

      assert.strictEqual(lastStatement?.resultKind, 'static');
      assert.ok(lastResultSet);
      assert.ok(lastResultSet.columns.length > 0);
      assert.strictEqual(unresolvedColumnCount({ ...result, columns: lastResultSet.columns }), 0);
      assert.deepStrictEqual(result.warnings, []);
    });
  }
});

function unresolvedColumnCount(result: DescribeResult): number {
  return result.columns.filter((column) => column.type === 'unknown').length;
}
