import type { DialectConfig } from "../types.js";

export const dialectConfig = {
  name: "duckdb",
  aliases: [],
  family: "duckdb",
  typeFamily: "duckdb",
  displayTypes: {
    bigint: "bigint",
    blob: "blob",
    boolean: "boolean",
    bytes: "blob",
    clob: "varchar",
    date: "date",
    datetime: "timestamp",
    decimal: "decimal(18, 3)",
    double: "double",
    duck_bit: "bit",
    integer: "integer",
    json: "json",
    jsonb: "json",
    nclob: "varchar",
    text: "varchar",
    time: "time",
    timestamp: "timestamp",
    timestamp_ms: "timestamp_ms",
    timestamp_ns: "timestamp_ns",
    timestamp_s: "timestamp_s",
    timestamptz: "timestamp with time zone",
    uuid: "uuid",
  },
  jdbcTypeMap: {
    ARRAY: "array<variant>",
    BIGINT: "bigint",
    BINARY: "bytes",
    BIT: "boolean",
    BLOB: "bytes",
    BOOLEAN: "boolean",
    CHAR: "text",
    CLOB: "text",
    DATALINK: "text",
    DATE: "date",
    DECIMAL: "decimal",
    DISTINCT: "variant",
    DOUBLE: "decimal",
    FLOAT: "decimal",
    INTEGER: "integer",
    JAVA_OBJECT: "variant",
    LONGNVARCHAR: "text",
    LONGVARBINARY: "bytes",
    LONGVARCHAR: "text",
    NCHAR: "text",
    NCLOB: "text",
    NULL: "unknown",
    NUMERIC: "decimal",
    NVARCHAR: "text",
    OTHER: "variant",
    REAL: "decimal",
    REF: "variant",
    REF_CURSOR: "variant",
    ROWID: "text",
    SMALLINT: "integer",
    SQLXML: "xml",
    STRUCT: "struct<>",
    TIME: "time",
    TIMESTAMP: "timestamp",
    TIMESTAMP_WITH_TIMEZONE: "timestamp",
    TIME_WITH_TIMEZONE: "time",
    TINYINT: "integer",
    VARBINARY: "bytes",
    VARCHAR: "text",
  },
  scalarFunctionTypes: {
    age: "interval",
    array_all: "boolean",
    array_any: "boolean",
    array_contains: "boolean",
    array_join: "text",
    array_length: "integer",
    array_lower: "integer",
    array_ndims: "integer",
    array_position: "integer",
    array_size: "integer",
    array_sum: "integer",
    array_to_string: "text",
    array_upper: "integer",
    as_array: "array<variant>",
    as_object: "object",
    as_varchar: "text",
    ascii: "integer",
    bit_length: "integer",
    byte_length: "integer",
    cardinality: "integer",
    cbrt: "decimal",
    char_length: "integer",
    character_length: "integer",
    contains: "boolean",
    convert_to: "bytes",
    cos: "decimal",
    current_catalog: "text",
    current_database: "text",
    current_datetime: "datetime",
    current_schema: "text",
    current_user: "text",
    currval: "bigint",
    date_parse: "timestamp",
    datetime: "datetime",
    day: "integer",
    degrees: "decimal",
    ends_with: "boolean",
    exp: "decimal",
    factorial: "integer",
    format_date: "text",
    from_base64: "bytes",
    gen_random_uuid: "uuid",
    generate_uuid: "uuid",
    grouping: "integer",
    grouping_id: "integer",
    hash: "integer",
    hex: "text",
    highlight: "text",
    hll_hash: "hll",
    hour: "integer",
    ieee_divide: "decimal",
    initcap: "text",
    instr: "integer",
    json_contains: "boolean",
    json_insert: "json",
    json_patch: "json",
    json_query: "json",
    json_query_array: "array<json>",
    json_remove: "json",
    json_replace: "json",
    json_set: "json",
    json_valid: "boolean",
    json_value: "text",
    json_value_array: "array<text>",
    jsonlength: "integer",
    julianday: "decimal",
    lastval: "bigint",
    length: "integer",
    list_contains: "boolean",
    ln: "decimal",
    locate: "integer",
    log: "decimal",
    log10: "decimal",
    lower: "text",
    ltrim: "text",
    md5: "text",
    minute: "integer",
    month: "integer",
    months_between: "decimal",
    newid: "uuid",
    nextval: "bigint",
    octet_length: "integer",
    overlay: "text",
    parse_json: "json",
    pi: "decimal",
    position: "integer",
    pow: "decimal",
    power: "decimal",
    printf: "text",
    quarter: "integer",
    radians: "decimal",
    rand: "decimal",
    random: "decimal",
    regexp_contains: "boolean",
    regexp_count: "integer",
    regexp_extract: "text",
    regexp_extract_all: "array<text>",
    regexp_instr: "integer",
    regexp_like: "boolean",
    regexp_match: "array<text>",
    regexp_matches: "array<text>",
    regexp_position: "integer",
    regexp_replace: "text",
    regexp_split: "array<text>",
    regexp_split_to_array: "array<text>",
    regexp_split_to_table: "text",
    regexp_substr: "text",
    replace: "text",
    rlike: "boolean",
    row_to_json: "json",
    rtrim: "text",
    safe_divide: "decimal",
    scope_identity: "integer",
    second: "integer",
    setval: "bigint",
    sha: "text",
    sha1: "text",
    sha224: "bytes",
    sha256: "bytes",
    sha384: "bytes",
    sha512: "bytes",
    sign: "integer",
    sin: "decimal",
    snippet: "text",
    split: "array<text>",
    split_part: "text",
    sqlite_version: "text",
    sqrt: "decimal",
    st_area: "decimal",
    st_asbinary: "bytes",
    st_asgeojson: "text",
    st_astext: "text",
    st_aswkb: "bytes",
    st_aswkt: "text",
    st_contains: "boolean",
    st_dimension: "integer",
    st_distance: "decimal",
    st_geogpoint: "geography",
    st_intersects: "boolean",
    st_length: "decimal",
    st_makeenvelope: "geometry",
    st_makepoint: "geometry",
    st_ndims: "integer",
    st_npoints: "integer",
    st_point: "geometry",
    st_srid: "integer",
    st_within: "boolean",
    st_x: "decimal",
    st_y: "decimal",
    starts_with: "boolean",
    str_split: "array<text>",
    string_to_array: "array<text>",
    strpos: "integer",
    substr: "text",
    substring: "text",
    tan: "decimal",
    time: "time",
    timestamp: "timestamp",
    to_array: "array<variant>",
    to_binary: "bytes",
    to_bitmap: "bitmap",
    to_boolean: "boolean",
    to_char: "text",
    to_decimal: "decimal",
    to_geography: "geography",
    to_geometry: "geometry",
    to_hex: "text",
    to_number: "decimal",
    to_object: "object",
    to_utf8: "bytes",
    to_variant: "variant",
    todate: "date",
    trim: "text",
    try_to_boolean: "boolean",
    try_to_decimal: "decimal",
    try_to_number: "decimal",
    typeof: "text",
    unhex: "bytes",
    upper: "text",
    user: "text",
    uuid: "uuid",
    uuid_string: "uuid",
    version: "text",
    week: "integer",
    xxhash64: "integer",
    year: "integer",
  },
  scalarFunctionTypePatterns: {
    "/^avg(?:_|$)/i": "double",
  },
  tableFunctions: {
    duckdb_columns: [
      {
        name: "database_name",
        type: "text",
      },
      {
        name: "schema_name",
        type: "text",
      },
      {
        name: "table_name",
        type: "text",
      },
      {
        name: "column_name",
        type: "text",
      },
      {
        name: "column_index",
        type: "integer",
      },
      {
        name: "data_type",
        type: "text",
      },
      {
        name: "is_nullable",
        type: "boolean",
      },
    ],
    duckdb_constraints: [
      {
        name: "database_name",
        type: "text",
      },
      {
        name: "database_oid",
        type: "integer",
      },
      {
        name: "schema_name",
        type: "text",
      },
      {
        name: "schema_oid",
        type: "integer",
      },
      {
        name: "table_name",
        type: "text",
      },
      {
        name: "table_oid",
        type: "integer",
      },
      {
        name: "constraint_index",
        type: "integer",
      },
      {
        name: "constraint_type",
        type: "text",
      },
      {
        name: "constraint_text",
        type: "text",
      },
      {
        name: "expression",
        type: "text",
      },
      {
        name: "constraint_column_indexes",
        type: "array<integer>",
      },
      {
        name: "constraint_column_names",
        type: "array<text>",
      },
    ],
    duckdb_databases: [
      {
        name: "database_name",
        type: "text",
      },
      {
        name: "database_oid",
        type: "integer",
      },
      {
        name: "path",
        type: "text",
      },
      {
        name: "internal",
        type: "boolean",
      },
    ],
    duckdb_extensions: [
      {
        name: "extension_name",
        type: "text",
      },
      {
        name: "loaded",
        type: "boolean",
      },
      {
        name: "installed",
        type: "boolean",
      },
      {
        name: "install_path",
        type: "text",
      },
      {
        name: "description",
        type: "text",
      },
      {
        name: "aliases",
        type: "array<text>",
      },
    ],
    duckdb_functions: [
      {
        name: "database_name",
        type: "text",
      },
      {
        name: "schema_name",
        type: "text",
      },
      {
        name: "function_name",
        type: "text",
      },
      {
        name: "function_type",
        type: "text",
      },
      {
        name: "return_type",
        type: "text",
      },
    ],
    duckdb_indexes: [
      {
        name: "database_name",
        type: "text",
      },
      {
        name: "schema_name",
        type: "text",
      },
      {
        name: "index_name",
        type: "text",
      },
      {
        name: "table_name",
        type: "text",
      },
      {
        name: "is_unique",
        type: "boolean",
      },
      {
        name: "sql",
        type: "text",
      },
    ],
    duckdb_keywords: [
      {
        name: "keyword_name",
        type: "text",
      },
      {
        name: "keyword_category",
        type: "text",
      },
    ],
    duckdb_memory: [
      {
        name: "tag",
        type: "text",
      },
      {
        name: "memory_usage_bytes",
        type: "integer",
      },
      {
        name: "temporary_storage_bytes",
        type: "integer",
      },
    ],
    duckdb_schemas: [
      {
        name: "database_name",
        type: "text",
      },
      {
        name: "schema_name",
        type: "text",
      },
      {
        name: "internal",
        type: "boolean",
      },
    ],
    duckdb_sequences: [
      {
        name: "database_name",
        type: "text",
      },
      {
        name: "schema_name",
        type: "text",
      },
      {
        name: "sequence_name",
        type: "text",
      },
      {
        name: "start_value",
        type: "integer",
      },
      {
        name: "min_value",
        type: "integer",
      },
      {
        name: "max_value",
        type: "integer",
      },
      {
        name: "increment_by",
        type: "integer",
      },
      {
        name: "cycle",
        type: "boolean",
      },
    ],
    duckdb_settings: [
      {
        name: "name",
        type: "text",
      },
      {
        name: "value",
        type: "text",
      },
      {
        name: "description",
        type: "text",
      },
      {
        name: "input_type",
        type: "text",
      },
      {
        name: "scope",
        type: "text",
      },
      {
        name: "aliases",
        type: "array<text>",
      },
    ],
    duckdb_tables: [
      {
        name: "database_name",
        type: "text",
      },
      {
        name: "schema_name",
        type: "text",
      },
      {
        name: "table_name",
        type: "text",
      },
      {
        name: "table_type",
        type: "text",
      },
      {
        name: "temporary",
        type: "boolean",
      },
    ],
    duckdb_types: [
      {
        name: "database_name",
        type: "text",
      },
      {
        name: "schema_name",
        type: "text",
      },
      {
        name: "type_name",
        type: "text",
      },
      {
        name: "type_size",
        type: "integer",
      },
      {
        name: "logical_type",
        type: "text",
      },
      {
        name: "labels",
        type: "array<text>",
      },
    ],
    duckdb_views: [
      {
        name: "database_name",
        type: "text",
      },
      {
        name: "schema_name",
        type: "text",
      },
      {
        name: "view_name",
        type: "text",
      },
      {
        name: "temporary",
        type: "boolean",
      },
      {
        name: "sql",
        type: "text",
      },
    ],
    glob: [
      {
        name: "file",
        type: "text",
      },
    ],
    json_each: [
      {
        name: "key",
        type: "text",
      },
      {
        name: "value",
        type: "json",
      },
      {
        name: "type",
        type: "text",
      },
      {
        name: "atom",
        type: "json",
      },
      {
        name: "id",
        type: "integer",
      },
      {
        name: "parent",
        type: "integer",
      },
      {
        name: "fullkey",
        type: "text",
      },
      {
        name: "path",
        type: "text",
      },
    ],
    json_tree: [
      {
        name: "key",
        type: "text",
      },
      {
        name: "value",
        type: "json",
      },
      {
        name: "type",
        type: "text",
      },
      {
        name: "atom",
        type: "json",
      },
      {
        name: "id",
        type: "integer",
      },
      {
        name: "parent",
        type: "integer",
      },
      {
        name: "fullkey",
        type: "text",
      },
      {
        name: "path",
        type: "text",
      },
    ],
    pragma_table_info: [
      {
        name: "cid",
        type: "integer",
      },
      {
        name: "name",
        type: "text",
      },
      {
        name: "type",
        type: "text",
      },
      {
        name: "notnull",
        type: "integer",
      },
      {
        name: "dflt_value",
        type: "text",
      },
      {
        name: "pk",
        type: "integer",
      },
    ],
    parquet_file_metadata: [
      {
        name: "file_name",
        type: "text",
      },
      {
        name: "created_by",
        type: "text",
      },
      {
        name: "num_rows",
        type: "integer",
      },
      {
        name: "num_row_groups",
        type: "integer",
      },
      {
        name: "format_version",
        type: "text",
      },
      {
        name: "encryption_algorithm",
        type: "text",
      },
      {
        name: "footer_signing_key_metadata",
        type: "text",
      },
    ],
    parquet_kv_metadata: [
      {
        name: "file_name",
        type: "text",
      },
      {
        name: "key",
        type: "text",
      },
      {
        name: "value",
        type: "bytes",
      },
    ],
    parquet_metadata: [
      {
        name: "file_name",
        type: "text",
      },
      {
        name: "row_group_id",
        type: "integer",
      },
      {
        name: "row_group_num_rows",
        type: "integer",
      },
      {
        name: "row_group_num_columns",
        type: "integer",
      },
      {
        name: "row_group_bytes",
        type: "integer",
      },
      {
        name: "column_id",
        type: "integer",
      },
      {
        name: "file_offset",
        type: "integer",
      },
      {
        name: "num_values",
        type: "integer",
      },
      {
        name: "path_in_schema",
        type: "text",
      },
      {
        name: "type",
        type: "text",
      },
      {
        name: "stats_min",
        type: "text",
      },
      {
        name: "stats_max",
        type: "text",
      },
      {
        name: "stats_null_count",
        type: "integer",
      },
      {
        name: "total_compressed_size",
        type: "integer",
      },
      {
        name: "total_uncompressed_size",
        type: "integer",
      },
    ],
    parquet_schema: [
      {
        name: "file_name",
        type: "text",
      },
      {
        name: "name",
        type: "text",
      },
      {
        name: "type",
        type: "text",
      },
      {
        name: "type_length",
        type: "text",
      },
      {
        name: "repetition_type",
        type: "text",
      },
      {
        name: "num_children",
        type: "integer",
      },
      {
        name: "converted_type",
        type: "text",
      },
      {
        name: "scale",
        type: "integer",
      },
      {
        name: "precision",
        type: "integer",
      },
      {
        name: "field_id",
        type: "integer",
      },
      {
        name: "logical_type",
        type: "text",
      },
    ],
    read_blob: [
      {
        name: "filename",
        type: "text",
      },
      {
        name: "content",
        type: "blob",
      },
    ],
    read_json_objects: [
      {
        name: "json",
        type: "json",
      },
    ],
    read_ndjson_objects: [
      {
        name: "json",
        type: "json",
      },
    ],
    read_text: [
      {
        name: "filename",
        type: "text",
      },
      {
        name: "content",
        type: "text",
      },
    ],
    regexp_matches: [
      {
        name: "$alias",
        type: "array<text>",
      },
    ],
    regexp_split_to_array: [
      {
        name: "$alias",
        type: "array<text>",
      },
    ],
  },
  aggregate: {
    countType: "bigint",
    avgDefault: "double",
    avgDecimal: "default",
    sumDecimal: "decimal38",
  },
  commonTypes: {
    text: "varchar",
    decimalInteger: "decimal",
  },
  cast: {
    adjustment: "none",
  },
  arithmetic: {
    decimalInteger: "tsqlDuckdbPrecision",
  },
  windowFunctionTypes: {
    row_number: "integer",
    rank: "integer",
    dense_rank: "integer",
    ntile: "integer",
    n_tile: "integer",
    percent_rank: "decimal",
    cume_dist: "decimal",
  },
  specialParameterTypes: {},
  specialColumnTypes: {
    current_date: "date",
    current_time: "time",
    current_timestamp: "timestamp",
    localtimestamp: "timestamp",
  },
  qualifiedSpecialColumnTypes: {},
  pseudoColumnTypes: {},
  generatedNames: {
    countStar: "count_star()",
    add: "duckdbParenthesized",
    upper: "duckdbQuotedCall",
  },
  scriptPreprocessor: "dotCommand",
  includeDirectives: [{ kind: "dot" }],
  complexTypeStyle: "angle",
  jdbcEscapeStyle: "standard",
  jdbcEscape: {
    ifnullFunction: "coalesce",
    temporalLiteral: "standard",
    executeCall: false,
    currentDateExpression: "current_date",
    currentTimeExpression: "current_time",
  },
  jdbcParameterMarker: "question",
  parserFallbacks: {
    createView: "postgres",
    tableMacro: "duckdb",
    embeddedSqlTableFunction: "tsql",
  },
  parameterizedTypeFormats: {
    decimal: "decimal({args})",
    dec: "decimal({args})",
    numeric: "decimal({args})",
    number: "decimal({args})",
  },
  literalTypes: {
    string: "text",
  },
  dynamicTableFunctions: {
    generateSeriesColumn: "$alias",
    rangeColumn: "$alias",
    enabledHandlers: ["generateSeries", "range", "fileColumns"],
  },
  serializedSelect: {},
  outputTypeOverrides: {
    "/^avg_/": "double",
    avg: "text",
    avg_null: "double",
    bind_add_equiv: "integer",
    bind_cast_equiv: "varchar",
    bind_coalesce_equiv: "integer",
    bool_any: "boolean",
    bool_sum: "hugeint",
    case_all_null: "integer",
    case_date_ts: "timestamp",
    case_nulls_typed: "varchar",
    case_num_text: "bigint",
    co_null_typed: "integer",
    co_num: "decimal",
    co_text: "varchar",
    collated_equal: "boolean",
    concat_empty: "varchar",
    concat_null: "integer",
    concat_widen: "varchar",
    count_distinct: "bigint",
    count_null: "bigint",
    count_star: "bigint",
    date_diff_days: "bigint",
    date_interval_plus: "timestamp",
    date_plus: "timestamp",
    dec_mul_dec: "decimal",
    dec_plus_int: "decimal",
    div_decimal: "double",
    div_decimal_int: "double",
    div_int: "double",
    duck_bignum_value: "bignum",
    duck_bit_value: "duck_bit",
    duck_enum_value: "enum('sad', 'ok')",
    duck_interval_value: "interval",
    duck_time_value: "time",
    duck_timestamp_ms_value: "timestamp_ms",
    duck_timestamp_ns_value: "timestamp_ns",
    duck_timestamp_s_value: "timestamp_s",
    duck_timestamptz_value: "timestamp with time zone",
    duck_ubigint_value: "ubigint",
    duck_uhugeint_value: "uhugeint",
    duck_uinteger_value: "uinteger",
    duck_utinyint_value: "utinyint",
    except_text: "varchar",
    hugeint_value: "hugeint",
    ifnull_text: "varchar(7)",
    int_array: "integer[]",
    intersect_null_text: "varchar",
    intersect_num: "bigint",
    isnull_text: "nchar(3)",
    json_items: "json",
    json_name: "varchar",
    json_scalar_bool: "json",
    json_scalar_null: "json",
    json_scalar_num: "json",
    json_type_name: "varchar",
    json_unquote_text: "varchar",
    large_bytes: "blob",
    large_text: "varchar",
    lit_null: "integer",
    map_value: "map(varchar, integer)",
    max_ts: "timestamp",
    min_date: "date",
    min_null: "varchar",
    minus_text: "varchar",
    mod_num: "integer",
    mul_num: "decimal",
    nested_int_array: "integer[][]",
    nullif_null_typed: "integer",
    nullif_num: "decimal",
    nullif_typed_null: "integer",
    nvl_text: "varchar2(7)",
    pred_between: "boolean",
    pred_eq: "boolean",
    pred_in: "boolean",
    pred_null: "boolean",
    rn: "bigint",
    round_num: "decimal",
    set_null_int: "integer",
    set_num: "bigint",
    set_temporal: "timestamp",
    set_text: "varchar",
    struct_value: 'struct(id integer, "name" varchar)',
    sum_null: "decimal",
    timezone_convert: "timestamp with time zone",
    ts_diff: "interval",
    ts_interval_plus: "timestamp",
    tstz_diff: "interval",
    unicode_text: "varchar",
    uuid_value: "uuid",
    win_avg: "double",
    win_sum: "decimal",
  },
  metadata: {
    builtinSchemaTables: [
      {
        schema: "information_schema",
        name: "character_sets",
        columns: [
          { name: "character_set_catalog", type: "text" },
          { name: "character_set_schema", type: "text" },
          { name: "character_set_name", type: "text" },
          { name: "character_repertoire", type: "text" },
          { name: "form_of_use", type: "text" },
          { name: "default_collate_catalog", type: "text" },
          { name: "default_collate_schema", type: "text" },
          { name: "default_collate_name", type: "text" },
        ],
      },
      {
        schema: "information_schema",
        name: "check_constraints",
        columns: [
          { name: "constraint_catalog", type: "text" },
          { name: "constraint_schema", type: "text" },
          { name: "constraint_name", type: "text" },
          { name: "check_clause", type: "text" },
        ],
      },
      {
        schema: "information_schema",
        name: "columns",
        columns: [
          { name: "table_catalog", type: "text" },
          { name: "table_schema", type: "text" },
          { name: "table_name", type: "text" },
          { name: "column_name", type: "text" },
          { name: "ordinal_position", type: "integer" },
          { name: "column_default", type: "text" },
          { name: "is_nullable", type: "text" },
          { name: "data_type", type: "text" },
          { name: "character_maximum_length", type: "integer" },
          { name: "character_octet_length", type: "integer" },
          { name: "numeric_precision", type: "integer" },
          { name: "numeric_precision_radix", type: "integer" },
          { name: "numeric_scale", type: "integer" },
          { name: "datetime_precision", type: "integer" },
          { name: "interval_type", type: "text" },
          { name: "interval_precision", type: "integer" },
          { name: "character_set_catalog", type: "text" },
          { name: "character_set_schema", type: "text" },
          { name: "character_set_name", type: "text" },
          { name: "collation_catalog", type: "text" },
          { name: "collation_schema", type: "text" },
          { name: "collation_name", type: "text" },
          { name: "domain_catalog", type: "text" },
          { name: "domain_schema", type: "text" },
          { name: "domain_name", type: "text" },
          { name: "udt_catalog", type: "text" },
          { name: "udt_schema", type: "text" },
          { name: "udt_name", type: "text" },
          { name: "scope_catalog", type: "text" },
          { name: "scope_schema", type: "text" },
          { name: "scope_name", type: "text" },
          { name: "maximum_cardinality", type: "integer" },
          { name: "dtd_identifier", type: "text" },
          { name: "is_self_referencing", type: "boolean" },
          { name: "is_identity", type: "boolean" },
          { name: "identity_generation", type: "text" },
          { name: "identity_start", type: "text" },
          { name: "identity_increment", type: "text" },
          { name: "identity_maximum", type: "text" },
          { name: "identity_minimum", type: "text" },
          { name: "identity_cycle", type: "boolean" },
          { name: "is_generated", type: "text" },
          { name: "generation_expression", type: "text" },
          { name: "is_updatable", type: "boolean" },
          { name: "column_comment", type: "text" },
        ],
      },
      {
        schema: "information_schema",
        name: "constraint_column_usage",
        columns: [
          { name: "table_catalog", type: "text" },
          { name: "table_schema", type: "text" },
          { name: "table_name", type: "text" },
          { name: "column_name", type: "text" },
          { name: "constraint_catalog", type: "text" },
          { name: "constraint_schema", type: "text" },
          { name: "constraint_name", type: "text" },
          { name: "constraint_type", type: "text" },
          { name: "constraint_text", type: "text" },
        ],
      },
      {
        schema: "information_schema",
        name: "constraint_table_usage",
        columns: [
          { name: "table_catalog", type: "text" },
          { name: "table_schema", type: "text" },
          { name: "table_name", type: "text" },
          { name: "constraint_catalog", type: "text" },
          { name: "constraint_schema", type: "text" },
          { name: "constraint_name", type: "text" },
          { name: "constraint_type", type: "text" },
        ],
      },
      {
        schema: "information_schema",
        name: "key_column_usage",
        columns: [
          { name: "constraint_catalog", type: "text" },
          { name: "constraint_schema", type: "text" },
          { name: "constraint_name", type: "text" },
          { name: "table_catalog", type: "text" },
          { name: "table_schema", type: "text" },
          { name: "table_name", type: "text" },
          { name: "column_name", type: "text" },
          { name: "ordinal_position", type: "integer" },
          { name: "position_in_unique_constraint", type: "integer" },
        ],
      },
      {
        schema: "information_schema",
        name: "referential_constraints",
        columns: [
          { name: "constraint_catalog", type: "text" },
          { name: "constraint_schema", type: "text" },
          { name: "constraint_name", type: "text" },
          { name: "unique_constraint_catalog", type: "text" },
          { name: "unique_constraint_schema", type: "text" },
          { name: "unique_constraint_name", type: "text" },
          { name: "match_option", type: "text" },
          { name: "update_rule", type: "text" },
          { name: "delete_rule", type: "text" },
        ],
      },
      {
        schema: "information_schema",
        name: "schemata",
        columns: [
          { name: "catalog_name", type: "text" },
          { name: "schema_name", type: "text" },
          { name: "schema_owner", type: "text" },
          { name: "default_character_set_catalog", type: "text" },
          { name: "default_character_set_schema", type: "text" },
          { name: "default_character_set_name", type: "text" },
          { name: "sql_path", type: "text" },
        ],
      },
      {
        schema: "information_schema",
        name: "table_constraints",
        columns: [
          { name: "constraint_catalog", type: "text" },
          { name: "constraint_schema", type: "text" },
          { name: "constraint_name", type: "text" },
          { name: "table_catalog", type: "text" },
          { name: "table_schema", type: "text" },
          { name: "table_name", type: "text" },
          { name: "constraint_type", type: "text" },
          { name: "is_deferrable", type: "text" },
          { name: "initially_deferred", type: "text" },
          { name: "enforced", type: "text" },
          { name: "nulls_distinct", type: "text" },
        ],
      },
      {
        schema: "information_schema",
        name: "tables",
        columns: [
          { name: "table_catalog", type: "text" },
          { name: "table_schema", type: "text" },
          { name: "table_name", type: "text" },
          { name: "table_type", type: "text" },
          { name: "self_referencing_column_name", type: "text" },
          { name: "reference_generation", type: "text" },
          { name: "user_defined_type_catalog", type: "text" },
          { name: "user_defined_type_schema", type: "text" },
          { name: "user_defined_type_name", type: "text" },
          { name: "is_insertable_into", type: "text" },
          { name: "is_typed", type: "text" },
          { name: "commit_action", type: "text" },
          { name: "table_comment", type: "text" },
        ],
      },
      {
        schema: "information_schema",
        name: "views",
        columns: [
          { name: "table_catalog", type: "text" },
          { name: "table_schema", type: "text" },
          { name: "table_name", type: "text" },
          { name: "view_definition", type: "text" },
          { name: "check_option", type: "text" },
          { name: "is_updatable", type: "text" },
          { name: "is_insertable_into", type: "text" },
          { name: "is_trigger_updatable", type: "text" },
          { name: "is_trigger_deletable", type: "text" },
          { name: "is_trigger_insertable_into", type: "text" },
        ],
      },
      {
        schema: "pg_catalog",
        name: "pg_am",
        columns: [
          { name: "oid", type: "integer" },
          { name: "amname", type: "text" },
          { name: "amhandler", type: "variant" },
          { name: "amtype", type: "text" },
        ],
      },
      {
        schema: "pg_catalog",
        name: "pg_attrdef",
        columns: [
          { name: "oid", type: "integer" },
          { name: "adrelid", type: "integer" },
          { name: "adnum", type: "integer" },
          { name: "adbin", type: "text" },
        ],
      },
      {
        schema: "pg_catalog",
        name: "pg_attribute",
        columns: [
          { name: "attrelid", type: "integer" },
          { name: "attname", type: "text" },
          { name: "atttypid", type: "integer" },
          { name: "attstattarget", type: "integer" },
          { name: "attlen", type: "variant" },
          { name: "attnum", type: "integer" },
          { name: "attndims", type: "integer" },
          { name: "attcacheoff", type: "integer" },
          { name: "atttypmod", type: "integer" },
          { name: "attbyval", type: "boolean" },
          { name: "attstorage", type: "variant" },
          { name: "attalign", type: "variant" },
          { name: "attnotnull", type: "boolean" },
          { name: "atthasdef", type: "boolean" },
          { name: "atthasmissing", type: "boolean" },
          { name: "attidentity", type: "text" },
          { name: "attgenerated", type: "text" },
          { name: "attisdropped", type: "boolean" },
          { name: "attislocal", type: "boolean" },
          { name: "attinhcount", type: "integer" },
          { name: "attcollation", type: "integer" },
          { name: "attcompression", type: "variant" },
          { name: "attacl", type: "variant" },
          { name: "attoptions", type: "variant" },
          { name: "attfdwoptions", type: "variant" },
          { name: "attmissingval", type: "variant" },
        ],
      },
      {
        schema: "pg_catalog",
        name: "pg_class",
        columns: [
          { name: "oid", type: "integer" },
          { name: "relname", type: "text" },
          { name: "relnamespace", type: "integer" },
          { name: "reltype", type: "integer" },
          { name: "reloftype", type: "integer" },
          { name: "relowner", type: "integer" },
          { name: "relam", type: "integer" },
          { name: "relfilenode", type: "integer" },
          { name: "reltablespace", type: "integer" },
          { name: "relpages", type: "integer" },
          { name: "reltuples", type: "decimal" },
          { name: "relallvisible", type: "integer" },
          { name: "reltoastrelid", type: "integer" },
          { name: "reltoastidxid", type: "integer" },
          { name: "relhasindex", type: "boolean" },
          { name: "relisshared", type: "boolean" },
          { name: "relpersistence", type: "text" },
          { name: "relkind", type: "text" },
          { name: "relnatts", type: "integer" },
          { name: "relchecks", type: "integer" },
          { name: "relhasoids", type: "boolean" },
          { name: "relhaspkey", type: "boolean" },
          { name: "relhasrules", type: "boolean" },
          { name: "relhastriggers", type: "boolean" },
          { name: "relhassubclass", type: "boolean" },
          { name: "relrowsecurity", type: "boolean" },
          { name: "relispopulated", type: "boolean" },
          { name: "relreplident", type: "variant" },
          { name: "relispartition", type: "boolean" },
          { name: "relrewrite", type: "integer" },
          { name: "relfrozenxid", type: "integer" },
          { name: "relminmxid", type: "variant" },
          { name: "relacl", type: "variant" },
          { name: "reloptions", type: "variant" },
          { name: "relpartbound", type: "variant" },
        ],
      },
      {
        schema: "pg_catalog",
        name: "pg_collation",
        columns: [
          { name: "oid", type: "integer" },
          { name: "collname", type: "text" },
        ],
      },
      {
        schema: "pg_catalog",
        name: "pg_constraint",
        columns: [
          { name: "oid", type: "integer" },
          { name: "conname", type: "text" },
          { name: "connamespace", type: "integer" },
          { name: "contype", type: "text" },
          { name: "condeferrable", type: "boolean" },
          { name: "condeferred", type: "boolean" },
          { name: "convalidated", type: "boolean" },
          { name: "conrelid", type: "integer" },
          { name: "contypid", type: "integer" },
          { name: "conindid", type: "integer" },
          { name: "conparentid", type: "integer" },
          { name: "confrelid", type: "integer" },
          { name: "confupdtype", type: "variant" },
          { name: "confdeltype", type: "variant" },
          { name: "confmatchtype", type: "variant" },
          { name: "conislocal", type: "boolean" },
          { name: "coninhcount", type: "integer" },
          { name: "connoinherit", type: "boolean" },
          { name: "conkey", type: "integer" },
          { name: "confkey", type: "variant" },
          { name: "conpfeqop", type: "variant" },
          { name: "conppeqop", type: "variant" },
          { name: "conffeqop", type: "variant" },
          { name: "conexclop", type: "variant" },
          { name: "conbin", type: "text" },
        ],
      },
      {
        schema: "pg_catalog",
        name: "pg_database",
        columns: [
          { name: "oid", type: "integer" },
          { name: "datname", type: "text" },
          { name: "datallowconn", type: "boolean" },
          { name: "datistemplate", type: "boolean" },
        ],
      },
      {
        schema: "pg_catalog",
        name: "pg_depend",
        columns: [
          { name: "classid", type: "integer" },
          { name: "objid", type: "integer" },
          { name: "objsubid", type: "integer" },
          { name: "refclassid", type: "integer" },
          { name: "refobjid", type: "integer" },
          { name: "refobjsubid", type: "integer" },
          { name: "deptype", type: "text" },
        ],
      },
      {
        schema: "pg_catalog",
        name: "pg_description",
        columns: [
          { name: "objoid", type: "integer" },
          { name: "classoid", type: "text" },
          { name: "objsubid", type: "integer" },
          { name: "description", type: "text" },
        ],
      },
      {
        schema: "pg_catalog",
        name: "pg_enum",
        columns: [
          { name: "oid", type: "variant" },
          { name: "enumtypid", type: "integer" },
          { name: "enumsortorder", type: "integer" },
          { name: "enumlabel", type: "text" },
        ],
      },
      {
        schema: "pg_catalog",
        name: "pg_index",
        columns: [
          { name: "indexrelid", type: "integer" },
          { name: "indrelid", type: "integer" },
          { name: "indnatts", type: "integer" },
          { name: "indnkeyatts", type: "integer" },
          { name: "indisunique", type: "boolean" },
          { name: "indisprimary", type: "boolean" },
          { name: "indisexclusion", type: "boolean" },
          { name: "indimmediate", type: "boolean" },
          { name: "indisclustered", type: "boolean" },
          { name: "indisvalid", type: "boolean" },
          { name: "indcheckxmin", type: "boolean" },
          { name: "indisready", type: "boolean" },
          { name: "indislive", type: "boolean" },
          { name: "indisreplident", type: "boolean" },
          { name: "indkey", type: "integer" },
          { name: "indcollation", type: "integer" },
          { name: "indclass", type: "integer" },
          { name: "indoption", type: "integer" },
          { name: "indexprs", type: "text" },
          { name: "indpred", type: "variant" },
        ],
      },
      {
        schema: "pg_catalog",
        name: "pg_indexes",
        columns: [
          { name: "schemaname", type: "text" },
          { name: "tablename", type: "text" },
          { name: "indexname", type: "text" },
          { name: "tablespace", type: "variant" },
          { name: "indexdef", type: "text" },
        ],
      },
      {
        schema: "pg_catalog",
        name: "pg_namespace",
        columns: [
          { name: "oid", type: "integer" },
          { name: "nspname", type: "text" },
          { name: "nspowner", type: "integer" },
          { name: "nspacl", type: "variant" },
        ],
      },
      {
        schema: "pg_catalog",
        name: "pg_prepared_statements",
        columns: [
          { name: "name", type: "text" },
          { name: "statement", type: "text" },
          { name: "prepare_time", type: "variant" },
          { name: "parameter_types", type: "text" },
          { name: "result_types", type: "text" },
          { name: "from_sql", type: "variant" },
          { name: "generic_plans", type: "variant" },
          { name: "custom_plans", type: "variant" },
        ],
      },
      {
        schema: "pg_catalog",
        name: "pg_proc",
        columns: [
          { name: "oid", type: "integer" },
          { name: "proname", type: "text" },
          { name: "pronamespace", type: "integer" },
          { name: "proowner", type: "variant" },
          { name: "prolang", type: "variant" },
          { name: "procost", type: "integer" },
          { name: "prorows", type: "integer" },
          { name: "provariadic", type: "text" },
          { name: "prosupport", type: "integer" },
          { name: "prokind", type: "text" },
          { name: "prosecdef", type: "boolean" },
          { name: "proleakproof", type: "boolean" },
          { name: "proisstrict", type: "boolean" },
          { name: "proretset", type: "boolean" },
          { name: "provolatile", type: "text" },
          { name: "proparallel", type: "text" },
          { name: "pronargs", type: "integer" },
          { name: "pronargdefaults", type: "integer" },
          { name: "prorettype", type: "text" },
          { name: "proargtypes", type: "text" },
          { name: "proallargtypes", type: "variant" },
          { name: "proargmodes", type: "variant" },
          { name: "proargnames", type: "text" },
          { name: "proargdefaults", type: "variant" },
          { name: "protrftypes", type: "variant" },
          { name: "prosrc", type: "variant" },
          { name: "probin", type: "variant" },
          { name: "prosqlbody", type: "text" },
          { name: "proconfig", type: "variant" },
          { name: "proacl", type: "variant" },
          { name: "proisagg", type: "boolean" },
        ],
      },
      {
        schema: "pg_catalog",
        name: "pg_sequence",
        columns: [
          { name: "seqrelid", type: "integer" },
          { name: "seqtypid", type: "integer" },
          { name: "seqstart", type: "integer" },
          { name: "seqincrement", type: "integer" },
          { name: "seqmax", type: "integer" },
          { name: "seqmin", type: "integer" },
          { name: "seqcache", type: "integer" },
          { name: "seqcycle", type: "boolean" },
        ],
      },
      {
        schema: "pg_catalog",
        name: "pg_sequences",
        columns: [
          { name: "schemaname", type: "text" },
          { name: "sequencename", type: "text" },
          { name: "sequenceowner", type: "text" },
          { name: "data_type", type: "integer" },
          { name: "start_value", type: "integer" },
          { name: "min_value", type: "integer" },
          { name: "max_value", type: "integer" },
          { name: "increment_by", type: "integer" },
          { name: "cycle", type: "boolean" },
          { name: "cache_size", type: "integer" },
          { name: "last_value", type: "integer" },
        ],
      },
      {
        schema: "pg_catalog",
        name: "pg_settings",
        columns: [
          { name: "name", type: "text" },
          { name: "setting", type: "text" },
          { name: "short_desc", type: "text" },
          { name: "vartype", type: "text" },
        ],
      },
      {
        schema: "pg_catalog",
        name: "pg_tables",
        columns: [
          { name: "schemaname", type: "text" },
          { name: "tablename", type: "text" },
          { name: "tableowner", type: "text" },
          { name: "tablespace", type: "variant" },
          { name: "hasindexes", type: "boolean" },
          { name: "hasrules", type: "boolean" },
          { name: "hastriggers", type: "boolean" },
        ],
      },
      {
        schema: "pg_catalog",
        name: "pg_tablespace",
        columns: [
          { name: "oid", type: "integer" },
          { name: "spcname", type: "text" },
          { name: "spcowner", type: "integer" },
          { name: "spcacl", type: "variant" },
          { name: "spcoptions", type: "variant" },
        ],
      },
      {
        schema: "pg_catalog",
        name: "pg_type",
        columns: [
          { name: "oid", type: "integer" },
          { name: "typname", type: "text" },
          { name: "typnamespace", type: "integer" },
          { name: "typowner", type: "integer" },
          { name: "typlen", type: "integer" },
          { name: "typbyval", type: "boolean" },
          { name: "typtype", type: "text" },
          { name: "typcategory", type: "text" },
          { name: "typispreferred", type: "boolean" },
          { name: "typisdefined", type: "boolean" },
          { name: "typdelim", type: "variant" },
          { name: "typrelid", type: "variant" },
          { name: "typsubscript", type: "variant" },
          { name: "typelem", type: "variant" },
          { name: "typarray", type: "variant" },
          { name: "typinput", type: "variant" },
          { name: "typoutput", type: "variant" },
          { name: "typreceive", type: "variant" },
          { name: "typsend", type: "variant" },
          { name: "typmodin", type: "variant" },
          { name: "typmodout", type: "variant" },
          { name: "typanalyze", type: "variant" },
          { name: "typalign", type: "text" },
          { name: "typstorage", type: "text" },
          { name: "typnotnull", type: "variant" },
          { name: "typbasetype", type: "variant" },
          { name: "typtypmod", type: "variant" },
          { name: "typndims", type: "variant" },
          { name: "typcollation", type: "variant" },
          { name: "typdefaultbin", type: "variant" },
          { name: "typdefault", type: "variant" },
          { name: "typacl", type: "variant" },
        ],
      },
      {
        schema: "pg_catalog",
        name: "pg_views",
        columns: [
          { name: "schemaname", type: "text" },
          { name: "viewname", type: "text" },
          { name: "viewowner", type: "text" },
          { name: "definition", type: "text" },
        ],
      },
    ],
    describeFunctionColumns: [
      { name: "Name", type: "text" },
      { name: "Description", type: "text" },
    ],
    explainColumns: [{ name: "QUERY PLAN", type: "text" }],
    snowflakeDescribeObjectColumns: {},
    showTableListingColumns: [
      { name: "created_on", type: "timestamp" },
      { name: "name", type: "text" },
      { name: "database_name", type: "text" },
      { name: "schema_name", type: "text" },
      { name: "kind", type: "text" },
      { name: "comment", type: "text" },
      { name: "cluster_by", type: "text" },
      { name: "rows", type: "integer" },
      { name: "bytes", type: "integer" },
      { name: "owner", type: "text" },
      { name: "retention_time", type: "integer" },
      { name: "automatic_clustering", type: "text" },
      { name: "change_tracking", type: "boolean" },
      { name: "search_optimization", type: "boolean" },
    ],
    commandResultColumns: [
      {
        pattern: "/^(?:list|ls)\\s+@/",
        columns: [
          { name: "name", type: "text" },
          { name: "size", type: "integer" },
          { name: "md5", type: "text" },
          { name: "last_modified", type: "timestamp" },
        ],
      },
      {
        pattern: "/^get\\s+@/",
        columns: [
          { name: "file", type: "text" },
          { name: "size", type: "integer" },
          { name: "status", type: "text" },
          { name: "message", type: "text" },
        ],
      },
      {
        pattern: "/^(?:remove|rm)\\s+@/",
        columns: [
          { name: "name", type: "text" },
          { name: "result", type: "text" },
        ],
      },
      {
        pattern: "/^list\\s+(?:file|jar|archive)\\b/",
        columns: [{ name: "resource", type: "text" }],
      },
    ],
  },
  diagnosticRules: {
    knownTableFunctionArgumentNames: ["file", "url"],
    virtualTableArgumentNames: ["highlight", "snippet", "bm25", "fts5vocab"],
  },
} satisfies DialectConfig;
