import type { DialectConfig } from "../types.js";

export const dialectConfig = {
  name: "sqlite",
  aliases: ["sqlite3"],
  family: "sqlite",
  typeFamily: "sqlite",
  displayTypes: {
    bigint: "integer",
    blob: "blob",
    boolean: "integer",
    bytes: "blob",
    clob: "text",
    date: "text",
    datetime: "text",
    decimal: "real",
    double: "real",
    integer: "integer",
    json: "text",
    jsonb: "blob",
    nclob: "text",
    text: "text",
    time: "text",
    timestamp: "text",
    timestamptz: "text",
    uuid: "text",
  },
  jdbcTypeMap: {
    ARRAY: "array<variant>",
    BIGINT: "bigint",
    BINARY: "bytes",
    BIT: "boolean",
    BLOB: "bytes",
    BOOLEAN: "boolean",
    CHAR: "text",
    CLOB: "text",
    DATALINK: "text",
    DATE: "date",
    DECIMAL: "decimal",
    DISTINCT: "variant",
    DOUBLE: "decimal",
    FLOAT: "decimal",
    INTEGER: "integer",
    JAVA_OBJECT: "variant",
    LONGNVARCHAR: "text",
    LONGVARBINARY: "bytes",
    LONGVARCHAR: "text",
    NCHAR: "text",
    NCLOB: "text",
    NULL: "unknown",
    NUMERIC: "decimal",
    NVARCHAR: "text",
    OTHER: "variant",
    REAL: "decimal",
    REF: "variant",
    REF_CURSOR: "variant",
    ROWID: "text",
    SMALLINT: "integer",
    SQLXML: "xml",
    STRUCT: "struct<>",
    TIME: "time",
    TIMESTAMP: "timestamp",
    TIMESTAMP_WITH_TIMEZONE: "timestamp",
    TIME_WITH_TIMEZONE: "time",
    TINYINT: "integer",
    VARBINARY: "bytes",
    VARCHAR: "text",
  },
  scalarFunctionTypes: {
    age: "interval",
    array_all: "boolean",
    array_any: "boolean",
    array_contains: "boolean",
    array_join: "text",
    array_length: "integer",
    array_lower: "integer",
    array_ndims: "integer",
    array_position: "integer",
    array_size: "integer",
    array_sum: "integer",
    array_to_string: "text",
    array_upper: "integer",
    as_array: "array<variant>",
    as_object: "object",
    as_varchar: "text",
    ascii: "integer",
    bit_length: "integer",
    byte_length: "integer",
    cardinality: "integer",
    cbrt: "decimal",
    char_length: "integer",
    character_length: "integer",
    contains: "boolean",
    convert_to: "bytes",
    cos: "decimal",
    current_catalog: "text",
    current_database: "text",
    current_datetime: "datetime",
    current_schema: "text",
    current_user: "text",
    currval: "bigint",
    date_parse: "timestamp",
    datetime: "datetime",
    day: "integer",
    degrees: "decimal",
    ends_with: "boolean",
    exp: "decimal",
    factorial: "integer",
    format_date: "text",
    from_base64: "bytes",
    gen_random_uuid: "uuid",
    generate_uuid: "uuid",
    grouping: "integer",
    grouping_id: "integer",
    hash: "integer",
    hex: "text",
    highlight: "text",
    hll_hash: "hll",
    hour: "integer",
    ieee_divide: "decimal",
    initcap: "text",
    instr: "integer",
    json_contains: "boolean",
    json_insert: "json",
    json_patch: "json",
    json_query: "json",
    json_query_array: "array<json>",
    json_remove: "json",
    json_replace: "json",
    json_set: "json",
    json_valid: "boolean",
    json_value: "text",
    json_value_array: "array<text>",
    jsonlength: "integer",
    julianday: "decimal",
    lastval: "bigint",
    length: "integer",
    list_contains: "boolean",
    ln: "decimal",
    locate: "integer",
    log: "decimal",
    log10: "decimal",
    lower: "text",
    ltrim: "text",
    md5: "text",
    minute: "integer",
    month: "integer",
    months_between: "decimal",
    newid: "uuid",
    nextval: "bigint",
    octet_length: "integer",
    overlay: "text",
    parse_json: "json",
    pi: "decimal",
    position: "integer",
    pow: "decimal",
    power: "decimal",
    printf: "text",
    quarter: "integer",
    radians: "decimal",
    rand: "decimal",
    random: "decimal",
    regexp_contains: "boolean",
    regexp_count: "integer",
    regexp_extract: "text",
    regexp_extract_all: "array<text>",
    regexp_instr: "integer",
    regexp_like: "boolean",
    regexp_match: "array<text>",
    regexp_matches: "array<text>",
    regexp_position: "integer",
    regexp_replace: "text",
    regexp_split: "array<text>",
    regexp_split_to_array: "array<text>",
    regexp_split_to_table: "text",
    regexp_substr: "text",
    replace: "text",
    rlike: "boolean",
    row_to_json: "json",
    rtrim: "text",
    safe_divide: "decimal",
    scope_identity: "integer",
    second: "integer",
    setval: "bigint",
    sha: "text",
    sha1: "text",
    sha224: "bytes",
    sha256: "bytes",
    sha384: "bytes",
    sha512: "bytes",
    sign: "integer",
    sin: "decimal",
    snippet: "text",
    split: "array<text>",
    split_part: "text",
    sqlite_version: "text",
    sqrt: "decimal",
    st_area: "decimal",
    st_asbinary: "bytes",
    st_asgeojson: "text",
    st_astext: "text",
    st_aswkb: "bytes",
    st_aswkt: "text",
    st_contains: "boolean",
    st_dimension: "integer",
    st_distance: "decimal",
    st_geogpoint: "geography",
    st_intersects: "boolean",
    st_length: "decimal",
    st_makeenvelope: "geometry",
    st_makepoint: "geometry",
    st_ndims: "integer",
    st_npoints: "integer",
    st_point: "geometry",
    st_srid: "integer",
    st_within: "boolean",
    st_x: "decimal",
    st_y: "decimal",
    starts_with: "boolean",
    str_split: "array<text>",
    string_to_array: "array<text>",
    strpos: "integer",
    substr: "text",
    substring: "text",
    tan: "decimal",
    time: "time",
    timestamp: "timestamp",
    to_array: "array<variant>",
    to_binary: "bytes",
    to_bitmap: "bitmap",
    to_boolean: "boolean",
    to_char: "text",
    to_decimal: "decimal",
    to_geography: "geography",
    to_geometry: "geometry",
    to_hex: "text",
    to_number: "decimal",
    to_object: "object",
    to_utf8: "bytes",
    to_variant: "variant",
    todate: "date",
    trim: "text",
    try_to_boolean: "boolean",
    try_to_decimal: "decimal",
    try_to_number: "decimal",
    typeof: "text",
    unhex: "bytes",
    upper: "text",
    user: "text",
    uuid: "uuid",
    uuid_string: "uuid",
    version: "text",
    week: "integer",
    xxhash64: "integer",
    year: "integer",
  },
  scalarFunctionTypePatterns: {},
  tableFunctions: {
    json_each: [
      {
        name: "key",
        type: "text",
      },
      {
        name: "value",
        type: "json",
      },
      {
        name: "type",
        type: "text",
      },
      {
        name: "atom",
        type: "json",
      },
      {
        name: "id",
        type: "integer",
      },
      {
        name: "parent",
        type: "integer",
      },
      {
        name: "fullkey",
        type: "text",
      },
      {
        name: "path",
        type: "text",
      },
    ],
    json_tree: [
      {
        name: "key",
        type: "text",
      },
      {
        name: "value",
        type: "json",
      },
      {
        name: "type",
        type: "text",
      },
      {
        name: "atom",
        type: "json",
      },
      {
        name: "id",
        type: "integer",
      },
      {
        name: "parent",
        type: "integer",
      },
      {
        name: "fullkey",
        type: "text",
      },
      {
        name: "path",
        type: "text",
      },
    ],
    pragma_table_info: [
      {
        name: "cid",
        type: "integer",
      },
      {
        name: "name",
        type: "text",
      },
      {
        name: "type",
        type: "text",
      },
      {
        name: "notnull",
        type: "integer",
      },
      {
        name: "dflt_value",
        type: "text",
      },
      {
        name: "pk",
        type: "integer",
      },
    ],
  },
  aggregate: {
    countType: "integer",
    avgDefault: "decimal",
    avgDecimal: "default",
    sumDecimal: "input",
  },
  commonTypes: {
    text: "none",
    decimalInteger: "none",
  },
  cast: {
    adjustment: "none",
  },
  arithmetic: {
    decimalInteger: "none",
  },
  windowFunctionTypes: {
    row_number: "integer",
    rank: "integer",
    dense_rank: "integer",
    ntile: "integer",
    n_tile: "integer",
    percent_rank: "decimal",
    cume_dist: "decimal",
  },
  specialParameterTypes: {},
  specialColumnTypes: {
    current_date: "date",
    current_time: "time",
    current_timestamp: "timestamp",
    localtimestamp: "timestamp",
    rowid: "integer",
    _rowid_: "integer",
    oid: "integer",
  },
  qualifiedSpecialColumnTypes: {},
  pseudoColumnTypes: {},
  generatedNames: {
    countStar: "count(*)",
    add: "compact",
    upper: "call",
  },
  scriptPreprocessor: "dotCommand",
  includeDirectives: [{ kind: "dot" }],
  complexTypeStyle: "angle",
  jdbcEscapeStyle: "standard",
  jdbcEscape: {
    ifnullFunction: "coalesce",
    temporalLiteral: "standard",
    executeCall: false,
    currentDateExpression: "current_date",
    currentTimeExpression: "current_time",
  },
  jdbcParameterMarker: "question",
  parserFallbacks: {
    createView: "postgres",
    tableMacro: "duckdb",
    embeddedSqlTableFunction: "tsql",
  },
  parameterizedTypeFormats: {
    decimal: "decimal({args})",
    dec: "decimal({args})",
    numeric: "decimal({args})",
    number: "decimal({args})",
  },
  literalTypes: {
    string: "text",
  },
  dynamicTableFunctions: {
    generateSeriesColumn: "value",
    rangeColumn: "$alias",
    enabledHandlers: ["generateSeries", "sqliteFts5Vocab", "sqlitePragma"],
  },
  selectStar: {},
  serializedSelect: {},
  outputTypeOverrides: {
    avg_null: "null",
    bind_add_equiv: "integer",
    bind_cast_equiv: "text",
    bind_coalesce_equiv: "integer",
    bool_sum: "integer",
    case_all_null: "null",
    case_date_ts: "text",
    case_nulls_typed: "text",
    case_num_text: "integer",
    co_null_typed: "integer",
    co_num: "integer",
    collated_equal: "integer",
    concat_empty: "text",
    concat_null: "null",
    concat_widen: "text",
    count_distinct: "integer",
    count_null: "integer",
    count_star: "integer",
    date_diff_days: "real",
    date_interval_plus: "text",
    dec_mul_dec: "real",
    dec_plus_int: "real",
    div_decimal: "real",
    div_decimal_int: "real",
    except_text: "text",
    ifnull_text: "varchar(7)",
    intersect_null_text: "null",
    intersect_num: "integer",
    isnull_text: "nchar(3)",
    json_array_value: "text",
    json_items: "text",
    json_items_text: "text",
    json_name: "text",
    json_object_value: "text",
    json_scalar_bool: "integer",
    json_scalar_null: "null",
    json_scalar_num: "integer",
    json_type_name: "text",
    json_unquote_text: "text",
    large_bytes: "blob",
    large_text: "text",
    max_ts: "text",
    min_date: "text",
    min_null: "null",
    minus_text: "text",
    mod_num: "integer",
    nested_json_value: "text",
    nullif_null_typed: "null",
    nullif_typed_null: "integer",
    nvl_text: "varchar2(7)",
    pred_between: "integer",
    pred_eq: "integer",
    pred_in: "integer",
    pred_null: "integer",
    random_blob_value: "blob",
    set_null_int: "null",
    set_num: "integer",
    set_temporal: "text",
    set_text: "text",
    sum_null: "null",
    timezone_convert: "text",
    ts_diff: "real",
    ts_interval_plus: "text",
    tz_text: "text",
    unicode_concat: "text",
    unicode_text: "text",
    zero_blob: "blob",
  },
  metadata: {
    sqliteRowidColumns: ["rowid", "_rowid_", "oid"],
    builtinSchemaTables: [
      {
        name: "sqlite_master",
        columns: [
          { name: "type", type: "text" },
          { name: "name", type: "text" },
          { name: "tbl_name", type: "text" },
          { name: "rootpage", type: "integer" },
          { name: "sql", type: "text" },
        ],
      },
      {
        name: "sqlite_schema",
        columns: [
          { name: "type", type: "text" },
          { name: "name", type: "text" },
          { name: "tbl_name", type: "text" },
          { name: "rootpage", type: "integer" },
          { name: "sql", type: "text" },
        ],
      },
      {
        name: "sqlite_temp_master",
        columns: [
          { name: "type", type: "text" },
          { name: "name", type: "text" },
          { name: "tbl_name", type: "text" },
          { name: "rootpage", type: "integer" },
          { name: "sql", type: "text" },
        ],
      },
      {
        name: "sqlite_temp_schema",
        columns: [
          { name: "type", type: "text" },
          { name: "name", type: "text" },
          { name: "tbl_name", type: "text" },
          { name: "rootpage", type: "integer" },
          { name: "sql", type: "text" },
        ],
      },
    ],
    describeFunctionColumns: [
      { name: "Name", type: "text" },
      { name: "Description", type: "text" },
    ],
    explainColumns: [
      { name: "addr", type: "integer" },
      { name: "opcode", type: "text" },
      { name: "p1", type: "integer" },
      { name: "p2", type: "integer" },
      { name: "p3", type: "integer" },
      { name: "p4", type: "text" },
      { name: "p5", type: "integer" },
      { name: "comment", type: "text" },
    ],
    snowflakeDescribeObjectColumns: {},
    showTableListingColumns: [
      { name: "created_on", type: "timestamp" },
      { name: "name", type: "text" },
      { name: "database_name", type: "text" },
      { name: "schema_name", type: "text" },
      { name: "kind", type: "text" },
      { name: "comment", type: "text" },
      { name: "cluster_by", type: "text" },
      { name: "rows", type: "integer" },
      { name: "bytes", type: "integer" },
      { name: "owner", type: "text" },
      { name: "retention_time", type: "integer" },
      { name: "automatic_clustering", type: "text" },
      { name: "change_tracking", type: "boolean" },
      { name: "search_optimization", type: "boolean" },
    ],
    commandResultColumns: [
      {
        pattern: "/^(?:list|ls)\\s+@/",
        columns: [
          { name: "name", type: "text" },
          { name: "size", type: "integer" },
          { name: "md5", type: "text" },
          { name: "last_modified", type: "timestamp" },
        ],
      },
      {
        pattern: "/^get\\s+@/",
        columns: [
          { name: "file", type: "text" },
          { name: "size", type: "integer" },
          { name: "status", type: "text" },
          { name: "message", type: "text" },
        ],
      },
      {
        pattern: "/^(?:remove|rm)\\s+@/",
        columns: [
          { name: "name", type: "text" },
          { name: "result", type: "text" },
        ],
      },
      {
        pattern: "/^list\\s+(?:file|jar|archive)\\b/",
        columns: [{ name: "resource", type: "text" }],
      },
    ],
  },
  diagnosticRules: {
    knownTableFunctionArgumentNames: ["file", "url"],
    virtualTableArgumentNames: ["highlight", "snippet", "bm25", "fts5vocab"],
    suppressSqliteRowid: true,
  },
} satisfies DialectConfig;
