import type { DialectConfig } from './types.js';

export const dialectConfig = {
  name: 'starrocks',
  aliases: [],
  family: 'mysql',
  typeFamily: 'mysql',
  displayTypes: {
    bigint: 'bigint',
    blob: 'longblob',
    boolean: 'tinyint(1)',
    bytes: 'varbinary(255)',
    clob: 'longtext',
    date: 'date',
    datetime: 'datetime',
    decimal: 'decimal',
    integer: 'int',
    json: 'json',
    jsonb: 'json',
    mysql_blob: 'blob',
    mysql_text: 'text',
    nclob: 'longtext',
    text: 'varchar(255)',
    time: 'time',
    timestamp: 'timestamp',
    timestamptz: 'timestamp',
    uuid: 'char(36)',
  },
  jdbcTypeMap: {
    ARRAY: 'json',
    BIGINT: 'bigint',
    BINARY: 'bytes',
    BIT: 'boolean',
    BLOB: 'bytes',
    BOOLEAN: 'boolean',
    CHAR: 'text',
    CLOB: 'text',
    DATALINK: 'text',
    DATE: 'date',
    DECIMAL: 'decimal',
    DISTINCT: 'variant',
    DOUBLE: 'decimal',
    FLOAT: 'decimal',
    INTEGER: 'integer',
    JAVA_OBJECT: 'json',
    LONGNVARCHAR: 'text',
    LONGVARBINARY: 'bytes',
    LONGVARCHAR: 'text',
    NCHAR: 'text',
    NCLOB: 'text',
    NULL: 'unknown',
    NUMERIC: 'decimal',
    NVARCHAR: 'text',
    OTHER: 'json',
    REAL: 'decimal',
    REF: 'variant',
    REF_CURSOR: 'variant',
    ROWID: 'text',
    SMALLINT: 'integer',
    SQLXML: 'text',
    STRUCT: 'json',
    TIME: 'time',
    TIMESTAMP: 'datetime',
    TIMESTAMP_WITH_TIMEZONE: 'datetime',
    TIME_WITH_TIMEZONE: 'time',
    TINYINT: 'integer',
    VARBINARY: 'bytes',
    VARCHAR: 'text',
  },
  scalarFunctionTypes: {
    age: 'interval',
    array_all: 'boolean',
    array_any: 'boolean',
    array_contains: 'boolean',
    array_join: 'text',
    array_length: 'integer',
    array_lower: 'integer',
    array_ndims: 'integer',
    array_position: 'integer',
    array_size: 'integer',
    array_sum: 'integer',
    array_to_string: 'text',
    array_upper: 'integer',
    as_array: 'array<variant>',
    as_object: 'object',
    as_varchar: 'text',
    ascii: 'integer',
    bit_length: 'integer',
    byte_length: 'integer',
    cardinality: 'integer',
    cbrt: 'decimal',
    char_length: 'integer',
    character_length: 'integer',
    contains: 'boolean',
    convert_to: 'bytes',
    cos: 'decimal',
    current_catalog: 'text',
    current_database: 'text',
    current_datetime: 'datetime',
    current_schema: 'text',
    current_user: 'text',
    currval: 'bigint',
    date_parse: 'timestamp',
    datetime: 'datetime',
    day: 'integer',
    degrees: 'decimal',
    ends_with: 'boolean',
    exp: 'decimal',
    factorial: 'integer',
    format_date: 'text',
    from_base64: 'bytes',
    gen_random_uuid: 'uuid',
    generate_uuid: 'uuid',
    grouping: 'integer',
    grouping_id: 'integer',
    hash: 'integer',
    hex: 'text',
    highlight: 'text',
    hll_hash: 'hll',
    hour: 'integer',
    ieee_divide: 'decimal',
    initcap: 'text',
    instr: 'integer',
    json_contains: 'boolean',
    json_insert: 'json',
    json_patch: 'json',
    json_query: 'json',
    json_query_array: 'array<json>',
    json_remove: 'json',
    json_replace: 'json',
    json_set: 'json',
    json_valid: 'boolean',
    json_value: 'text',
    json_value_array: 'array<text>',
    jsonlength: 'integer',
    julianday: 'decimal',
    lastval: 'bigint',
    length: 'integer',
    list_contains: 'boolean',
    ln: 'decimal',
    locate: 'integer',
    log: 'decimal',
    log10: 'decimal',
    lower: 'text',
    ltrim: 'text',
    md5: 'text',
    minute: 'integer',
    month: 'integer',
    months_between: 'decimal',
    newid: 'uuid',
    nextval: 'bigint',
    octet_length: 'integer',
    overlay: 'text',
    parse_json: 'json',
    pi: 'decimal',
    position: 'integer',
    pow: 'decimal',
    power: 'decimal',
    printf: 'text',
    quarter: 'integer',
    radians: 'decimal',
    rand: 'decimal',
    random: 'decimal',
    regexp_contains: 'boolean',
    regexp_count: 'integer',
    regexp_extract: 'text',
    regexp_extract_all: 'array<text>',
    regexp_instr: 'integer',
    regexp_like: 'boolean',
    regexp_match: 'array<text>',
    regexp_matches: 'array<text>',
    regexp_position: 'integer',
    regexp_replace: 'text',
    regexp_split: 'array<text>',
    regexp_split_to_array: 'array<text>',
    regexp_split_to_table: 'text',
    regexp_substr: 'text',
    replace: 'text',
    rlike: 'boolean',
    row_to_json: 'json',
    rtrim: 'text',
    safe_divide: 'decimal',
    scope_identity: 'integer',
    second: 'integer',
    setval: 'bigint',
    sha: 'text',
    sha1: 'text',
    sha224: 'bytes',
    sha256: 'bytes',
    sha384: 'bytes',
    sha512: 'bytes',
    sign: 'integer',
    sin: 'decimal',
    snippet: 'text',
    split: 'array<text>',
    split_part: 'text',
    sqlite_version: 'text',
    sqrt: 'decimal',
    st_area: 'decimal',
    st_asbinary: 'bytes',
    st_asgeojson: 'text',
    st_astext: 'text',
    st_aswkb: 'bytes',
    st_aswkt: 'text',
    st_contains: 'boolean',
    st_dimension: 'integer',
    st_distance: 'decimal',
    st_geogpoint: 'geography',
    st_intersects: 'boolean',
    st_length: 'decimal',
    st_makeenvelope: 'geometry',
    st_makepoint: 'geometry',
    st_ndims: 'integer',
    st_npoints: 'integer',
    st_point: 'geometry',
    st_srid: 'integer',
    st_within: 'boolean',
    st_x: 'decimal',
    st_y: 'decimal',
    starts_with: 'boolean',
    str_split: 'array<text>',
    string_to_array: 'array<text>',
    strpos: 'integer',
    substr: 'text',
    substring: 'text',
    tan: 'decimal',
    time: 'time',
    timestamp: 'timestamp',
    to_array: 'array<variant>',
    to_binary: 'bytes',
    to_bitmap: 'bitmap',
    to_boolean: 'boolean',
    to_char: 'text',
    to_decimal: 'decimal',
    to_geography: 'geography',
    to_geometry: 'geometry',
    to_hex: 'text',
    to_number: 'decimal',
    to_object: 'object',
    to_utf8: 'bytes',
    to_variant: 'variant',
    todate: 'date',
    trim: 'text',
    try_to_boolean: 'boolean',
    try_to_decimal: 'decimal',
    try_to_number: 'decimal',
    typeof: 'text',
    unhex: 'bytes',
    upper: 'text',
    user: 'text',
    uuid: 'uuid',
    uuid_string: 'uuid',
    version: 'text',
    week: 'integer',
    xxhash64: 'integer',
    year: 'integer',
  },
  tableFunctions: {
    "aclexplode": [{ name: "grantor", type: "oid" }, { name: "grantee", type: "oid" }, { name: "privilege_type", type: "text" }, { name: "is_grantable", type: "boolean" }],
    "current_setting": [{ name: "$alias", type: "text" }],
    "duckdb_columns": [{ name: "database_name", type: "text" }, { name: "schema_name", type: "text" }, { name: "table_name", type: "text" }, { name: "column_name", type: "text" }, { name: "column_index", type: "integer" }, { name: "data_type", type: "text" }, { name: "is_nullable", type: "boolean" }],
    "duckdb_constraints": [{ name: "database_name", type: "text" }, { name: "database_oid", type: "integer" }, { name: "schema_name", type: "text" }, { name: "schema_oid", type: "integer" }, { name: "table_name", type: "text" }, { name: "table_oid", type: "integer" }, { name: "constraint_index", type: "integer" }, { name: "constraint_type", type: "text" }, { name: "constraint_text", type: "text" }, { name: "expression", type: "text" }, { name: "constraint_column_indexes", type: "array<integer>" }, { name: "constraint_column_names", type: "array<text>" }],
    "duckdb_databases": [{ name: "database_name", type: "text" }, { name: "database_oid", type: "integer" }, { name: "path", type: "text" }, { name: "internal", type: "boolean" }],
    "duckdb_extensions": [{ name: "extension_name", type: "text" }, { name: "loaded", type: "boolean" }, { name: "installed", type: "boolean" }, { name: "install_path", type: "text" }, { name: "description", type: "text" }, { name: "aliases", type: "array<text>" }],
    "duckdb_functions": [{ name: "database_name", type: "text" }, { name: "schema_name", type: "text" }, { name: "function_name", type: "text" }, { name: "function_type", type: "text" }, { name: "return_type", type: "text" }],
    "duckdb_indexes": [{ name: "database_name", type: "text" }, { name: "schema_name", type: "text" }, { name: "index_name", type: "text" }, { name: "table_name", type: "text" }, { name: "is_unique", type: "boolean" }, { name: "sql", type: "text" }],
    "duckdb_keywords": [{ name: "keyword_name", type: "text" }, { name: "keyword_category", type: "text" }],
    "duckdb_memory": [{ name: "tag", type: "text" }, { name: "memory_usage_bytes", type: "integer" }, { name: "temporary_storage_bytes", type: "integer" }],
    "duckdb_schemas": [{ name: "database_name", type: "text" }, { name: "schema_name", type: "text" }, { name: "internal", type: "boolean" }],
    "duckdb_sequences": [{ name: "database_name", type: "text" }, { name: "schema_name", type: "text" }, { name: "sequence_name", type: "text" }, { name: "start_value", type: "integer" }, { name: "min_value", type: "integer" }, { name: "max_value", type: "integer" }, { name: "increment_by", type: "integer" }, { name: "cycle", type: "boolean" }],
    "duckdb_settings": [{ name: "name", type: "text" }, { name: "value", type: "text" }, { name: "description", type: "text" }, { name: "input_type", type: "text" }, { name: "scope", type: "text" }, { name: "aliases", type: "array<text>" }],
    "duckdb_tables": [{ name: "database_name", type: "text" }, { name: "schema_name", type: "text" }, { name: "table_name", type: "text" }, { name: "table_type", type: "text" }, { name: "temporary", type: "boolean" }],
    "duckdb_types": [{ name: "database_name", type: "text" }, { name: "schema_name", type: "text" }, { name: "type_name", type: "text" }, { name: "type_size", type: "integer" }, { name: "logical_type", type: "text" }, { name: "labels", type: "array<text>" }],
    "duckdb_views": [{ name: "database_name", type: "text" }, { name: "schema_name", type: "text" }, { name: "view_name", type: "text" }, { name: "temporary", type: "boolean" }, { name: "sql", type: "text" }],
    "flatten": [{ name: "seq", type: "integer" }, { name: "key", type: "text" }, { name: "path", type: "text" }, { name: "index", type: "integer" }, { name: "value", type: "variant" }, { name: "this", type: "variant" }],
    "generator": [],
    "generate_date_array": [{ name: "$alias", type: "date" }],
    "generate_subscripts": [{ name: "$alias", type: "integer" }],
    "generate_timestamp_array": [{ name: "$alias", type: "timestamp" }],
    "glob": [{ name: "file", type: "text" }],
    "infer_schema": [{ name: "expression", type: "text" }, { name: "column_name", type: "text" }, { name: "type", type: "text" }, { name: "nullable", type: "boolean" }, { name: "filenames", type: "array<text>" }, { name: "order_id", type: "integer" }],
    "json_array_elements": [{ name: "$alias", type: "json" }],
    "json_array_elements_text": [{ name: "$alias", type: "text" }],
    "json_each": [{ name: "key", type: "text" }, { name: "value", type: "json" }, { name: "type", type: "text" }, { name: "atom", type: "json" }, { name: "id", type: "integer" }, { name: "parent", type: "integer" }, { name: "fullkey", type: "text" }, { name: "path", type: "text" }],
    "json_each_text": [{ name: "key", type: "text" }, { name: "value", type: "text" }],
    "json_object_keys": [{ name: "$alias", type: "text" }],
    "json_tree": [{ name: "key", type: "text" }, { name: "value", type: "json" }, { name: "type", type: "text" }, { name: "atom", type: "json" }, { name: "id", type: "integer" }, { name: "parent", type: "integer" }, { name: "fullkey", type: "text" }, { name: "path", type: "text" }],
    "jsonb_array_elements": [{ name: "$alias", type: "json" }],
    "jsonb_array_elements_text": [{ name: "$alias", type: "text" }],
    "jsonb_each": [{ name: "key", type: "text" }, { name: "value", type: "json" }],
    "jsonb_each_text": [{ name: "key", type: "text" }, { name: "value", type: "text" }],
    "jsonb_object_keys": [{ name: "$alias", type: "text" }],
    "opendatasource": [{ name: "$alias", type: "unknown" }],
    "openquery": [{ name: "$alias", type: "unknown" }],
    "openrowset": [{ name: "$alias", type: "unknown" }],
    "parquet_file_metadata": [{ name: "file_name", type: "text" }, { name: "created_by", type: "text" }, { name: "num_rows", type: "integer" }, { name: "num_row_groups", type: "integer" }, { name: "format_version", type: "text" }, { name: "encryption_algorithm", type: "text" }, { name: "footer_signing_key_metadata", type: "text" }],
    "parquet_kv_metadata": [{ name: "file_name", type: "text" }, { name: "key", type: "text" }, { name: "value", type: "bytes" }],
    "parquet_metadata": [{ name: "file_name", type: "text" }, { name: "row_group_id", type: "integer" }, { name: "row_group_num_rows", type: "integer" }, { name: "row_group_num_columns", type: "integer" }, { name: "row_group_bytes", type: "integer" }, { name: "column_id", type: "integer" }, { name: "file_offset", type: "integer" }, { name: "num_values", type: "integer" }, { name: "path_in_schema", type: "text" }, { name: "type", type: "text" }, { name: "stats_min", type: "text" }, { name: "stats_max", type: "text" }, { name: "stats_null_count", type: "integer" }, { name: "total_compressed_size", type: "integer" }, { name: "total_uncompressed_size", type: "integer" }],
    "parquet_schema": [{ name: "file_name", type: "text" }, { name: "name", type: "text" }, { name: "type", type: "text" }, { name: "type_length", type: "text" }, { name: "repetition_type", type: "text" }, { name: "num_children", type: "integer" }, { name: "converted_type", type: "text" }, { name: "scale", type: "integer" }, { name: "precision", type: "integer" }, { name: "field_id", type: "integer" }, { name: "logical_type", type: "text" }],
    "pg_available_extension_versions": [{ name: "name", type: "text" }, { name: "version", type: "text" }, { name: "installed", type: "boolean" }, { name: "superuser", type: "boolean" }, { name: "trusted", type: "boolean" }, { name: "relocatable", type: "boolean" }, { name: "schema", type: "text" }, { name: "requires", type: "array<text>" }, { name: "comment", type: "text" }],
    "pg_get_keywords": [{ name: "word", type: "text" }, { name: "catcode", type: "text" }, { name: "catdesc", type: "text" }, { name: "baredesc", type: "text" }],
    "pg_get_object_address": [{ name: "classid", type: "oid" }, { name: "objid", type: "oid" }, { name: "objsubid", type: "integer" }],
    "pg_logical_slot_get_changes": [{ name: "lsn", type: "pg_lsn" }, { name: "xid", type: "xid" }, { name: "data", type: "text" }],
    "pg_logical_slot_peek_changes": [{ name: "lsn", type: "pg_lsn" }, { name: "xid", type: "xid" }, { name: "data", type: "text" }],
    "pg_ls_archive_statusdir": [{ name: "name", type: "text" }, { name: "size", type: "bigint" }, { name: "modification", type: "timestamp" }],
    "pg_ls_dir": [{ name: "$alias", type: "text" }],
    "pg_ls_logdir": [{ name: "name", type: "text" }, { name: "size", type: "bigint" }, { name: "modification", type: "timestamp" }],
    "pg_ls_tmpdir": [{ name: "name", type: "text" }, { name: "size", type: "bigint" }, { name: "modification", type: "timestamp" }],
    "pg_ls_waldir": [{ name: "name", type: "text" }, { name: "size", type: "bigint" }, { name: "modification", type: "timestamp" }],
    "pg_options_to_table": [{ name: "option_name", type: "text" }, { name: "option_value", type: "text" }],
    "pg_read_binary_file": [{ name: "$alias", type: "bytes" }],
    "pg_read_file": [{ name: "$alias", type: "text" }],
    "pg_stat_file": [{ name: "size", type: "bigint" }, { name: "access", type: "timestamp" }, { name: "modification", type: "timestamp" }, { name: "change", type: "timestamp" }, { name: "creation", type: "timestamp" }, { name: "isdir", type: "boolean" }],
    "pg_stat_get_activity": [{ name: "datid", type: "oid" }, { name: "pid", type: "integer" }, { name: "usesysid", type: "oid" }, { name: "application_name", type: "text" }, { name: "state", type: "text" }, { name: "query", type: "text" }, { name: "query_start", type: "timestamp" }, { name: "backend_start", type: "timestamp" }, { name: "xact_start", type: "timestamp" }, { name: "waiting", type: "boolean" }],
    "pg_stat_get_snapshot_timestamp": [{ name: "$alias", type: "timestamp" }],
    "pg_timezone_abbrevs": [{ name: "abbrev", type: "text" }, { name: "utc_offset", type: "interval" }, { name: "is_dst", type: "boolean" }],
    "pg_timezone_names": [{ name: "name", type: "text" }, { name: "abbrev", type: "text" }, { name: "utc_offset", type: "interval" }, { name: "is_dst", type: "boolean" }],
    "pragma_table_info": [{ name: "cid", type: "integer" }, { name: "name", type: "text" }, { name: "type", type: "text" }, { name: "notnull", type: "integer" }, { name: "dflt_value", type: "text" }, { name: "pk", type: "integer" }],
    "read_blob": [{ name: "filename", type: "text" }, { name: "content", type: "blob" }],
    "read_json_objects": [{ name: "json", type: "json" }],
    "read_ndjson_objects": [{ name: "json", type: "json" }],
    "read_text": [{ name: "filename", type: "text" }, { name: "content", type: "text" }],
    "regexp_matches": [{ name: "$alias", type: "array<text>" }],
    "regexp_split_to_array": [{ name: "$alias", type: "array<text>" }],
    "regexp_split_to_table": [{ name: "$alias", type: "text" }],
    "split_to_table": [{ name: "seq", type: "integer" }, { name: "index", type: "integer" }, { name: "value", type: "text" }],
    "string_split": [{ name: "value", type: "text" }],
    "ts_debug": [{ name: "alias", type: "text" }, { name: "description", type: "text" }, { name: "token", type: "text" }, { name: "dictionaries", type: "text[]" }, { name: "dictionary", type: "text" }, { name: "lexemes", type: "text[]" }],
  },
  aggregate: {
    "countType": "integer",
    "avgDefault": "decimal",
    "avgDecimal": "default",
    "sumDecimal": "input",
  },
  commonTypes: {
    "text": "none",
    "decimalInteger": "none",
  },
  cast: {
    "adjustment": "none",
  },
  arithmetic: {
    "decimalInteger": "none",
  },
  windowFunctionTypes: {
    "row_number": "integer",
    "rank": "integer",
    "dense_rank": "integer",
    "ntile": "integer",
    "n_tile": "integer",
    "percent_rank": "decimal",
    "cume_dist": "decimal",
  },
  specialParameterTypes: {},
  specialColumnTypes: {
    "current_date": "date",
    "current_time": "time",
    "current_timestamp": "timestamp",
    "localtimestamp": "timestamp",
  },
  qualifiedSpecialColumnTypes: {},
  pseudoColumnTypes: {},
  generatedNames: {
    "countStar": "count(*)",
    "add": "compact",
    "upper": "call",
  },
  scriptPreprocessor: 'mysqlDelimiter',
  includeDirectives: [{ kind: 'mysql' }],
  complexTypeStyle: 'angle',
  jdbcEscapeStyle: 'mysql',
  outputTypeOverrides: {
    "ifnull_text": "varchar(7)",
    "isnull_text": "nchar(3)",
    "min_date": "date",
    "nvl_text": "varchar2(7)",
  },
  metadata: {},
  diagnosticRules: {
    knownTableFunctionArgumentNames: [
      'file',
      'url',
    ],
    virtualTableArgumentNames: [
      'highlight',
      'snippet',
      'bm25',
      'fts5vocab',
    ],
  },
} satisfies DialectConfig;
